package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bodega generated by hbm2java
 */

@Entity
@Table(name = "bodega")
public class Bodega  implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long cia;
	
	@Column(name = "codigo")
    private String codigo;
	
	@Column(name = "descripcion")
    private String descripcion;

    public Bodega() {
    }

    public Bodega(Long cia, String codigo, String descripcion) {
       this.cia = cia;
       this.codigo = codigo;
       this.descripcion = descripcion;
    }
   
    public Long getCia() {
        return this.cia;
    }
    
    public void setCia(Long cia) {
        this.cia = cia;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


