package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CertificadosDet generated by hbm2java
 */
@Entity
@Table(name = "certificados_det")
public class CertificadosDet implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "tipocert")
	private String tipoCert;
	
	@Column(name = "numerocert")
	private String numeroCert;
	
	@Column(name = "item")
	private Integer item;
	
	@Column(name = "tipodoc")
	private String tipoDoc;
	
	@Column(name = "numerodoc")
	private String numeroDoc;
	
	@Column(name = "fechadoc")
	private Date fechaDoc;
	
	@Column(name = "vendedor")
	private String vendedor;
	
	@Column(name = "valordoc")
	private Float valorDoc;
	
	@Column(name = "valorutilizado")
	private Float valorUtlizado;
	
	@Column(name = "observaciones")
	private String observaciones;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public CertificadosDet() {
	}

	public CertificadosDet(Long cia) {
		this.cia = cia;
	}

	public CertificadosDet(Long cia, String tipoCert, String numeroCert, Integer item, String tipoDoc, String numeroDoc,
			Date fechaDoc, String vendedor, Float valorDoc, Float valorUtlizado, String observaciones,
			Character statReg, String usuario, Date fechaIngreso) {
		this.cia = cia;
		this.tipoCert = tipoCert;
		this.numeroCert = numeroCert;
		this.item = item;
		this.tipoDoc = tipoDoc;
		this.numeroDoc = numeroDoc;
		this.fechaDoc = fechaDoc;
		this.vendedor = vendedor;
		this.valorDoc = valorDoc;
		this.valorUtlizado = valorUtlizado;
		this.observaciones = observaciones;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getTipoCert() {
		return this.tipoCert;
	}

	public void setTipocert(String tipoCert) {
		this.tipoCert = tipoCert;
	}

	public String getNumeroCert() {
		return this.numeroCert;
	}

	public void setNumeroCert(String numeroCert) {
		this.numeroCert = numeroCert;
	}

	public Integer getItem() {
		return this.item;
	}

	public void setItem(Integer item) {
		this.item = item;
	}

	public String getTipoDoc() {
		return this.tipoDoc;
	}

	public void setTipoDoc(String tipoDoc) {
		this.tipoDoc = tipoDoc;
	}

	public String getNumeroDoc() {
		return this.numeroDoc;
	}

	public void setNumeroDoc(String numeroDoc) {
		this.numeroDoc = numeroDoc;
	}

	public Date getFechaDoc() {
		return this.fechaDoc;
	}

	public void setFechaDoc(Date fechaDoc) {
		this.fechaDoc = fechaDoc;
	}

	public String getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(String vendedor) {
		this.vendedor = vendedor;
	}

	public Float getValorDoc() {
		return this.valorDoc;
	}

	public void setValorDoc(Float valorDoc) {
		this.valorDoc = valorDoc;
	}

	public Float getValorUtlizado() {
		return this.valorUtlizado;
	}

	public void setValorUtlizado(Float valorUtlizado) {
		this.valorUtlizado = valorUtlizado;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
