package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Certificados generated by hbm2java
 */
@Entity
@Table(name = "certificados")
public class Certificados implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "tipocert")
	private String tipoCert;
	
	@Column(name = "numerocert")
	private String numeroCert;
	
	@Column(name = "fechacert")
	private Date fechaCert;
	
	@Column(name = "vence")
	private Date vence;
	
	@Column(name = "vendedor")
	private String vendedor;
	
	@Column(name = "nit")
	private String nit;
	
	@Column(name = "comprador")
	private String comprador;
	
	@Column(name = "beneficiario")
	private String beneficiario;
	
	@Column(name = "valor")
	private Float valor;
	
	@Column(name = "tipodoc")
	private String tipoDoc;
	
	@Column(name = "numerodoc")
	private String numeroDoc;
	
	@Column(name = "fechadoc")
	private Date fechaDoc;
	
	@Column(name = "observaciones")
	private String observaciones;
	
	@Column(name = "exclusivo")
	private Character exclusivo;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public Certificados() {
	}

	public Certificados(Long cia) {
		this.cia = cia;
	}

	public Certificados(Long cia, String tipoCert, String numeroCert, Date fechaCert, Date vence, String vendedor,
			String nit, String comprador, String beneficiario, Float valor, String tipoDoc, String numeroDoc,
			Date fechaDoc, String observaciones, Character exclusivo, Character statReg, String usuario,
			Date fechaIngreso) {
		this.cia = cia;
		this.tipoCert = tipoCert;
		this.numeroCert = numeroCert;
		this.fechaCert = fechaCert;
		this.vence = vence;
		this.vendedor = vendedor;
		this.nit = nit;
		this.comprador = comprador;
		this.beneficiario = beneficiario;
		this.valor = valor;
		this.tipoDoc = tipoDoc;
		this.numeroDoc = numeroDoc;
		this.fechaDoc = fechaDoc;
		this.observaciones = observaciones;
		this.exclusivo = exclusivo;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getTipoCert() {
		return this.tipoCert;
	}

	public void setTipoCert(String tipoCert) {
		this.tipoCert = tipoCert;
	}

	public String getNumeroCert() {
		return this.numeroCert;
	}

	public void setNumeroCert(String numeroCert) {
		this.numeroCert = numeroCert;
	}

	public Date getFechaCert() {
		return this.fechaCert;
	}

	public void setFechaCert(Date fechaCert) {
		this.fechaCert = fechaCert;
	}

	public Date getVence() {
		return this.vence;
	}

	public void setVence(Date vence) {
		this.vence = vence;
	}

	public String getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(String vendedor) {
		this.vendedor = vendedor;
	}

	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	public String getComprador() {
		return this.comprador;
	}

	public void setComprador(String comprador) {
		this.comprador = comprador;
	}

	public String getBeneficiario() {
		return this.beneficiario;
	}

	public void setBeneficiario(String beneficiario) {
		this.beneficiario = beneficiario;
	}

	public Float getValor() {
		return this.valor;
	}

	public void setValor(Float valor) {
		this.valor = valor;
	}

	public String getTipoDoc() {
		return this.tipoDoc;
	}

	public void setTipoDoc(String tipoDoc) {
		this.tipoDoc = tipoDoc;
	}

	public String getNumeroDoc() {
		return this.numeroDoc;
	}

	public void setNumeroDoc(String numeroDoc) {
		this.numeroDoc = numeroDoc;
	}

	public Date getFechaDoc() {
		return this.fechaDoc;
	}

	public void setFechaDoc(Date fechaDoc) {
		this.fechaDoc = fechaDoc;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Character getExclusivo() {
		return this.exclusivo;
	}

	public void setExclusivo(Character exclusivo) {
		this.exclusivo = exclusivo;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
