package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cheques generated by hbm2java
 */
@Entity
@Table(name = "cheques")
public class Cheques implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "nitcliente")
	private String nitCliente;
	
	@Column(name = "factura")
	private String factura;
	
	@Column(name = "banco")
	private String banco;
	
	@Column(name = "nombres")
	private String nombres;
	
	@Column(name = "numero_ch")
	private String numeroCh;
	
	@Column(name = "numero_cta")
	private String numeroCta;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "comprador")
	private String comprador;
	
	@Column(name = "telefono")
	private String telefono;
	
	@Column(name = "autorizacion")
	private String autorizacion;
	
	@Column(name = "valor_ch")
	private Float valorCh;
	
	@Column(name = "diferencia")
	private Float diferencia;
	
	@Column(name = "stat_chq")
	private Character statChq;
	
	@Column(name = "valor")
	private Float valor;
	
	@Column(name = "no_rechazo")
	private Short noRechazo;
	
	@Column(name = "observaciones")
	private String observaciones;
	
	@Column(name = "fechacobro")
	private Date fechaCobro;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public Cheques() {
	}

	public Cheques(Long cia) {
		this.cia = cia;
	}

	public Cheques(Long cia, String nitCliente, String factura, String banco, String nombres, String numeroCh,
			String numeroCta, Date fecha, String comprador, String telefono, String autorizacion, Float valorCh,
			Float diferencia, Character statChq, Float valor, Short noRechazo, String observaciones, Date fechaCobro,
			Character statReg, String usuario, Date fechaIngreso) {
		this.cia = cia;
		this.nitCliente = nitCliente;
		this.factura = factura;
		this.banco = banco;
		this.nombres = nombres;
		this.numeroCh = numeroCh;
		this.numeroCta = numeroCta;
		this.fecha = fecha;
		this.comprador = comprador;
		this.telefono = telefono;
		this.autorizacion = autorizacion;
		this.valorCh = valorCh;
		this.diferencia = diferencia;
		this.statChq = statChq;
		this.valor = valor;
		this.noRechazo = noRechazo;
		this.observaciones = observaciones;
		this.fechaCobro = fechaCobro;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getNitCliente() {
		return this.nitCliente;
	}

	public void setNitCliente(String nitCliente) {
		this.nitCliente = nitCliente;
	}

	public String getFactura() {
		return this.factura;
	}

	public void setFactura(String factura) {
		this.factura = factura;
	}

	public String getBanco() {
		return this.banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	public String getNombres() {
		return this.nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getNumeroCh() {
		return this.numeroCh;
	}

	public void setNumeroCh(String numeroCh) {
		this.numeroCh = numeroCh;
	}

	public String getNumeroCta() {
		return this.numeroCta;
	}

	public void setNumeroCta(String numeroCta) {
		this.numeroCta = numeroCta;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getComprador() {
		return this.comprador;
	}

	public void setComprador(String comprador) {
		this.comprador = comprador;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getAutorizacion() {
		return this.autorizacion;
	}

	public void setAutorizacion(String autorizacion) {
		this.autorizacion = autorizacion;
	}

	public Float getValorCh() {
		return this.valorCh;
	}

	public void setValorCh(Float valorCh) {
		this.valorCh = valorCh;
	}

	public Float getDiferencia() {
		return this.diferencia;
	}

	public void setDiferencia(Float diferencia) {
		this.diferencia = diferencia;
	}

	public Character getStatChq() {
		return this.statChq;
	}

	public void setStatChq(Character statChq) {
		this.statChq = statChq;
	}

	public Float getValor() {
		return this.valor;
	}

	public void setValor(Float valor) {
		this.valor = valor;
	}

	public Short getNoRechazo() {
		return this.noRechazo;
	}

	public void setNoRechazo(Short noRechazo) {
		this.noRechazo = noRechazo;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Date getFechaCobro() {
		return this.fechaCobro;
	}

	public void setFechaCobro(Date fechaCobro) {
		this.fechaCobro = fechaCobro;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
