package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clientessincompras generated by hbm2java
 */
@Entity
@Table(name = "clientessincompras")
public class ClientesSinCompras implements java.io.Serializable {

	@Id
	@Column(name = "id_clientes")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idClientes;
	
	@Column(name = "codigo")
	private String codigo;
	
	@Column(name = "cant_compras")
	private Float cantCompras;

	public ClientesSinCompras() {
	}

	public ClientesSinCompras(String codigo, Float cantCompras) {
		this.codigo = codigo;
		this.cantCompras = cantCompras;
	}

	public Long getIdClientes() {
		return this.idClientes;
	}

	public void setIdClientes(Long idClientes) {
		this.idClientes = idClientes;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Float getCantCompras() {
		return this.cantCompras;
	}

	public void setCantCompras(Float cantCompras) {
		this.cantCompras = cantCompras;
	}

}
