package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Correlativo generated by hbm2java
 */
@Entity
@Table(name = "correlativo")
public class Correlativo implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "codigo")
	private String codigo;
	
	@Column(name = "descripcion")
	private String descripcion;
	
	@Column(name = "corr")
	private String corr;
	
	@Column(name = "tipo")
	private char tipo;
	
	@Column(name = "no_autorizacion")
	private String noAutorizacion;
	
	@Column(name = "fecha_autorizacion")
	private Date fechaAutorizacion;
	
	@Column(name = "coor_inicial")
	private Float coorInicial;
	
	@Column(name = "corr_final")
	private Float corrFinal;
	
	@Column(name = "status")
	private String status;
	
	@Column(name = "alerta")
	private String alerta;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public Correlativo() {
	}

	public Correlativo(Long cia, String codigo, String descripcion, String corr, char tipo) {
		this.cia = cia;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.corr = corr;
		this.tipo = tipo;
	}

	public Correlativo(Long cia, String codigo, String descripcion, String corr, char tipo, String noAutorizacion,
			Date fechaAutorizacion, Float coorInicial, Float corrFinal, String status, String alerta, Character statReg,
			Date fechaIngreso) {
		this.cia = cia;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.corr = corr;
		this.tipo = tipo;
		this.noAutorizacion = noAutorizacion;
		this.fechaAutorizacion = fechaAutorizacion;
		this.coorInicial = coorInicial;
		this.corrFinal = corrFinal;
		this.status = status;
		this.alerta = alerta;
		this.statReg = statReg;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCorr() {
		return this.corr;
	}

	public void setCorr(String corr) {
		this.corr = corr;
	}

	public char getTipo() {
		return this.tipo;
	}

	public void setTipo(char tipo) {
		this.tipo = tipo;
	}

	public String getNoAutorizacion() {
		return this.noAutorizacion;
	}

	public void setNoAutorizacion(String noAutorizacion) {
		this.noAutorizacion = noAutorizacion;
	}

	public Date getFechaAutorizacion() {
		return this.fechaAutorizacion;
	}

	public void setFechaAutorizacion(Date fechaAutorizacion) {
		this.fechaAutorizacion = fechaAutorizacion;
	}

	public Float getCoorInicial() {
		return this.coorInicial;
	}

	public void setCoorInicial(Float coorInicial) {
		this.coorInicial = coorInicial;
	}

	public Float getCorrFinal() {
		return this.corrFinal;
	}

	public void setCorrFinal(Float corrFinal) {
		this.corrFinal = corrFinal;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getAlerta() {
		return this.alerta;
	}

	public void setAlerta(String alerta) {
		this.alerta = alerta;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
