package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CotizaD generated by hbm2java
 */
@Entity
@Table(name = "cotiza_d")
public class CotizaD implements java.io.Serializable {

	@Id
	@Column(name = "id_cotiza_d")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idCotizaD;
	
	@Column(name = "tipo")
	private String tipo;
	
	@Column(name = "num_dcto")
	private String numDcto;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "descripcion")
	private String descripcion;
	
	@Column(name = "debe")
	private Float debe;
	
	@Column(name = "pu")
	private Float pu;
	
	@Column(name = "valor")
	private Float valor;
	
	@Column(name = "dctolin")
	private Float dctoLin;
	
	@Column(name = "anio")
	private String anio;
	
	@Column(name = "nopieza")
	private String noPieza;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public CotizaD() {
	}

	public CotizaD(String tipo, String numDcto, String codArt, String descripcion, Float debe, Float pu, Float valor,
			Float dctoLin, String anio, String noPieza, Character statReg, String usuario, Date fechaIngreso) {
		this.tipo = tipo;
		this.numDcto = numDcto;
		this.codArt = codArt;
		this.descripcion = descripcion;
		this.debe = debe;
		this.pu = pu;
		this.valor = valor;
		this.dctoLin = dctoLin;
		this.anio = anio;
		this.noPieza = noPieza;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getIdCotizaD() {
		return this.idCotizaD;
	}

	public void setIdCotizaD(Long idCotizaD) {
		this.idCotizaD = idCotizaD;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getNumDcto() {
		return this.numDcto;
	}

	public void setNumDcto(String numDcto) {
		this.numDcto = numDcto;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Float getDebe() {
		return this.debe;
	}

	public void setDebe(Float debe) {
		this.debe = debe;
	}

	public Float getPu() {
		return this.pu;
	}

	public void setPu(Float pu) {
		this.pu = pu;
	}

	public Float getValor() {
		return this.valor;
	}

	public void setValor(Float valor) {
		this.valor = valor;
	}

	public Float getDctoLin() {
		return this.dctoLin;
	}

	public void setDctoLin(Float dctoLin) {
		this.dctoLin = dctoLin;
	}

	public String getAnio() {
		return this.anio;
	}

	public void setAnio(String anio) {
		this.anio = anio;
	}

	public String getNoPieza() {
		return this.noPieza;
	}

	public void setNoPieza(String noPieza) {
		this.noPieza = noPieza;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
