package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cotiza generated by hbm2java
 */
@Entity
@Table(name = "cotiza")
public class Cotiza implements java.io.Serializable {

	@Id
	@Column(name = "id_cotiza")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idCotiza;
	
	@Column(name = "num_dcto")
	private String numDcto;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "descripcion")
	private String descripcion;
	
	@Column(name = "debe")
	private Float debe;
	
	@Column(name = "pu")
	private Float pu;
	
	@Column(name = "valor")
	private Float valor;
	
	@Column(name = "item")
	private Float item;
	
	@Column(name = "dctolin")
	private Float dctoLin;
	
	@Column(name = "cia")
	private Float cia;
	
	@Column(name = "registro")
	private String registro;
	
	@Column(name = "tipo")
	private String tipo;

	public Cotiza() {
	}

	public Cotiza(String numDcto, String codArt, String descripcion, Float debe, Float pu, Float valor, Float item,
			Float dctoLin, Float cia, String registro, String tipo) {
		this.numDcto = numDcto;
		this.codArt = codArt;
		this.descripcion = descripcion;
		this.debe = debe;
		this.pu = pu;
		this.valor = valor;
		this.item = item;
		this.dctoLin = dctoLin;
		this.cia = cia;
		this.registro = registro;
		this.tipo = tipo;
	}

	public Long getIdCotiza() {
		return this.idCotiza;
	}

	public void setIdCotiza(Long idCotiza) {
		this.idCotiza = idCotiza;
	}

	public String getNumDcto() {
		return this.numDcto;
	}

	public void setNumDcto(String numDcto) {
		this.numDcto = numDcto;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Float getDebe() {
		return this.debe;
	}

	public void setDebe(Float debe) {
		this.debe = debe;
	}

	public Float getPu() {
		return this.pu;
	}

	public void setPu(Float pu) {
		this.pu = pu;
	}

	public Float getValor() {
		return this.valor;
	}

	public void setValor(Float valor) {
		this.valor = valor;
	}

	public Float getItem() {
		return this.item;
	}

	public void setItem(Float item) {
		this.item = item;
	}

	public Float getDctoLin() {
		return this.dctoLin;
	}

	public void setDctoLin(Float dctoLin) {
		this.dctoLin = dctoLin;
	}

	public Float getCia() {
		return this.cia;
	}

	public void setCia(Float cia) {
		this.cia = cia;
	}

	public String getRegistro() {
		return this.registro;
	}

	public void setRegistro(String registro) {
		this.registro = registro;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
