package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * CotizaH generated by hbm2java
 */
@Entity
@Table(name = "cotiza_h")
public class CotizaH implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "tipo")
	private String tipo;
	
	@Column(name = "numero")
	private String numero;
	
	@Column(name = "nitfa")
	private String nitFa;
	
	@Column(name = "nombrefa")
	private String nombreFa;
	
	@Column(name = "dirfa")
	private String dirFa;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "vendedor")
	private String vendedor;
	
	@Column(name = "sub")
	private Float sub;
	
	@Column(name = "iva")
	private Float iva;
	
	@Column(name = "debe")
	private Float debe;
	
	@Column(name = "haber")
	private Float haber;
	
	@Column(name = "descuento")
	private Float descuento;
	
	@Column(name = "mes")
	private String mes;
	
	@Column(name = "year")
	private String year;
	
	@Column(name = "vigencia")
	private Integer vigencia;
	
	@Column(name = "numerofa")
	private String numeroFa;
	
	@Column(name = "para")
	private String para;
	
	@Column(name = "fax")
	private String fax;
	
	@Column(name = "observaciones")
	private String observaciones;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public CotizaH() {
	}

	public CotizaH(Long cia) {
		this.cia = cia;
	}

	public CotizaH(Long cia, String tipo, String numero, String nitFa, String nombreFa, String dirFa, Date fecha,
			String vendedor, Float sub, Float iva, Float debe, Float haber, Float descuento, String mes, String year,
			Integer vigencia, String numeroFa, String para, String fax, String observaciones, Character statReg,
			String usuario, Date fechaIngreso) {
		this.cia = cia;
		this.tipo = tipo;
		this.numero = numero;
		this.nitFa = nitFa;
		this.nombreFa = nombreFa;
		this.dirFa = dirFa;
		this.fecha = fecha;
		this.vendedor = vendedor;
		this.sub = sub;
		this.iva = iva;
		this.debe = debe;
		this.haber = haber;
		this.descuento = descuento;
		this.mes = mes;
		this.year = year;
		this.vigencia = vigencia;
		this.numeroFa = numeroFa;
		this.para = para;
		this.fax = fax;
		this.observaciones = observaciones;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getNitFa() {
		return this.nitFa;
	}

	public void setNitFa(String nitFa) {
		this.nitFa = nitFa;
	}

	public String getNombreFa() {
		return this.nombreFa;
	}

	public void setNombreFa(String nombreFa) {
		this.nombreFa = nombreFa;
	}

	public String getDirFa() {
		return this.dirFa;
	}

	public void setDirFa(String dirFa) {
		this.dirFa = dirFa;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(String vendedor) {
		this.vendedor = vendedor;
	}

	public Float getSub() {
		return this.sub;
	}

	public void setSub(Float sub) {
		this.sub = sub;
	}

	public Float getIva() {
		return this.iva;
	}

	public void setIva(Float iva) {
		this.iva = iva;
	}

	public Float getDebe() {
		return this.debe;
	}

	public void setDebe(Float debe) {
		this.debe = debe;
	}

	public Float getHaber() {
		return this.haber;
	}

	public void setHaber(Float haber) {
		this.haber = haber;
	}

	public Float getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Float descuento) {
		this.descuento = descuento;
	}

	public String getMes() {
		return this.mes;
	}

	public void setMes(String mes) {
		this.mes = mes;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public Integer getVigencia() {
		return this.vigencia;
	}

	public void setVigencia(Integer vigencia) {
		this.vigencia = vigencia;
	}

	public String getNumeroFa() {
		return this.numeroFa;
	}

	public void setNumeroFa(String numeroFa) {
		this.numeroFa = numeroFa;
	}

	public String getPara() {
		return this.para;
	}

	public void setPara(String para) {
		this.para = para;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
