package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dctos generated by hbm2java
 */
@Entity
@Table(name = "dctos")
public class Dctos implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "tipo")
	private String tipo;
	
	@Column(name = "bodega")
	private String bodega;
	
	@Column(name = "numero")
	private String numero;
	
	@Column(name = "codigo")
	private String codigo;
	
	@Column(name = "nitfa")
	private String nitFa;
	
	@Column(name = "nombrefa")
	private String nombreFa;
	
	@Column(name = "dirfa")
	private String dirFa;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "vendedor")
	private String vendedor;
	
	@Column(name = "afecta")
	private String afecta;
	
	@Column(name = "dctofac")
	private Float dctoFac;
	
	@Column(name = "descuento")
	private Float descuento;
	
	@Column(name = "dias_credito")
	private Integer diasCredito;
	
	@Column(name = "sub")
	private Float sub;
	
	@Column(name = "iva")
	private Float iva;
	
	@Column(name = "debe")
	private Float debe;
	
	@Column(name = "haber")
	private Float haber;
	
	@Column(name = "mes")
	private String mes;
	
	@Column(name = "year")
	private String year;
	
	@Column(name = "campo")
	private String campo;
	
	@Column(name = "anulado")
	private boolean anulado;
	
	@Column(name = "vence")
	private Date vence;
	
	@Column(name = "efectivo")
	private Float efectivo;
	
	@Column(name = "cheque")
	private Float cheque;
	
	@Column(name = "credito")
	private Float credito;
	
	@Column(name = "tarjeta")
	private Float tarjeta;
	
	@Column(name = "otros")
	private Float otros;
	
	@Column(name = "ncheque")
	private String nCheque;
	
	@Column(name = "ordent")
	private String ordenT;
	
	@Column(name = "banco")
	private String banco;
	
	@Column(name = "cuenta")
	private String cuenta;
	
	@Column(name = "ntarjeta")
	private String nTarjeta;
	
	@Column(name = "vencetarjeta")
	private Date venceTarjeta;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario_desc")
	private String usuarioDesc;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public Dctos() {
	}

	public Dctos(Long cia, boolean anulado) {
		this.cia = cia;
		this.anulado = anulado;
	}

	public Dctos(Long cia, String tipo, String bodega, String numero, String codigo, String nitFa, String nombreFa,
			String dirFa, Date fecha, String vendedor, String afecta, Float dctoFac, Float descuento,
			Integer diasCredito, Float sub, Float iva, Float debe, Float haber, String mes, String year, String campo,
			boolean anulado, Date vence, Float efectivo, Float cheque, Float credito, Float tarjeta, Float otros,
			String nCheque, String ordenT, String banco, String cuenta, String nTarjeta, Date venceTarjeta,
			Character statReg, String usuarioDesc, String usuario, Date fechaIngreso) {
		this.cia = cia;
		this.tipo = tipo;
		this.bodega = bodega;
		this.numero = numero;
		this.codigo = codigo;
		this.nitFa = nitFa;
		this.nombreFa = nombreFa;
		this.dirFa = dirFa;
		this.fecha = fecha;
		this.vendedor = vendedor;
		this.afecta = afecta;
		this.dctoFac = dctoFac;
		this.descuento = descuento;
		this.diasCredito = diasCredito;
		this.sub = sub;
		this.iva = iva;
		this.debe = debe;
		this.haber = haber;
		this.mes = mes;
		this.year = year;
		this.campo = campo;
		this.anulado = anulado;
		this.vence = vence;
		this.efectivo = efectivo;
		this.cheque = cheque;
		this.credito = credito;
		this.tarjeta = tarjeta;
		this.otros = otros;
		this.nCheque = nCheque;
		this.ordenT = ordenT;
		this.banco = banco;
		this.cuenta = cuenta;
		this.nTarjeta = nTarjeta;
		this.venceTarjeta = venceTarjeta;
		this.statReg = statReg;
		this.usuarioDesc = usuarioDesc;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getBodega() {
		return this.bodega;
	}

	public void setBodega(String bodega) {
		this.bodega = bodega;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNitFa() {
		return this.nitFa;
	}

	public void setNitFa(String nitFa) {
		this.nitFa = nitFa;
	}

	public String getNombreFa() {
		return this.nombreFa;
	}

	public void setNombreFa(String nombreFa) {
		this.nombreFa = nombreFa;
	}

	public String getDirFa() {
		return this.dirFa;
	}

	public void setDirFa(String dirFa) {
		this.dirFa = dirFa;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(String vendedor) {
		this.vendedor = vendedor;
	}

	public String getAfecta() {
		return this.afecta;
	}

	public void setAfecta(String afecta) {
		this.afecta = afecta;
	}

	public Float getDctoFac() {
		return this.dctoFac;
	}

	public void setDctoFac(Float dctoFac) {
		this.dctoFac = dctoFac;
	}

	public Float getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Float descuento) {
		this.descuento = descuento;
	}

	public Integer getDiasCredito() {
		return this.diasCredito;
	}

	public void setDiasCredito(Integer diasCredito) {
		this.diasCredito = diasCredito;
	}

	public Float getSub() {
		return this.sub;
	}

	public void setSub(Float sub) {
		this.sub = sub;
	}

	public Float getIva() {
		return this.iva;
	}

	public void setIva(Float iva) {
		this.iva = iva;
	}

	public Float getDebe() {
		return this.debe;
	}

	public void setDebe(Float debe) {
		this.debe = debe;
	}

	public Float getHaber() {
		return this.haber;
	}

	public void setHaber(Float haber) {
		this.haber = haber;
	}

	public String getMes() {
		return this.mes;
	}

	public void setMes(String mes) {
		this.mes = mes;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getCampo() {
		return this.campo;
	}

	public void setCampo(String campo) {
		this.campo = campo;
	}

	public boolean isAnulado() {
		return this.anulado;
	}

	public void setAnulado(boolean anulado) {
		this.anulado = anulado;
	}

	public Date getVence() {
		return this.vence;
	}

	public void setVence(Date vence) {
		this.vence = vence;
	}

	public Float getEfectivo() {
		return this.efectivo;
	}

	public void setEfectivo(Float efectivo) {
		this.efectivo = efectivo;
	}

	public Float getCheque() {
		return this.cheque;
	}

	public void setCheque(Float cheque) {
		this.cheque = cheque;
	}

	public Float getCredito() {
		return this.credito;
	}

	public void setCredito(Float credito) {
		this.credito = credito;
	}

	public Float getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Float tarjeta) {
		this.tarjeta = tarjeta;
	}

	public Float getOtros() {
		return this.otros;
	}

	public void setOtros(Float otros) {
		this.otros = otros;
	}

	public String getNCheque() {
		return this.nCheque;
	}

	public void setNCheque(String nCheque) {
		this.nCheque = nCheque;
	}

	public String getOrdenT() {
		return this.ordenT;
	}

	public void setOrdenT(String ordenT) {
		this.ordenT = ordenT;
	}

	public String getBanco() {
		return this.banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	public String getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	public String getNTarjeta() {
		return this.nTarjeta;
	}

	public void setNTarjeta(String nTarjeta) {
		this.nTarjeta = nTarjeta;
	}

	public Date getVenceTarjeta() {
		return this.venceTarjeta;
	}

	public void setVenceTarjeta(Date venceTarjeta) {
		this.venceTarjeta = venceTarjeta;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuarioDesc() {
		return this.usuarioDesc;
	}

	public void setUsuarioDesc(String usuarioDesc) {
		this.usuarioDesc = usuarioDesc;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
