package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Depto generated by hbm2java
 */
@Entity
@Table(name = "depto")
public class Depto implements java.io.Serializable {

	@Id
	@Column(name = "id_depto")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idDepto;
	
	@Column(name = "codigo")
	private String codigo;
	
	@Column(name = "concepto")
	private String concepto;

	public Depto() {
	}

	public Depto(String codigo) {
		this.codigo = codigo;
	}

	public Depto(String codigo, String concepto) {
		this.codigo = codigo;
		this.concepto = concepto;
	}

	public Long getIdDepto() {
		return this.idDepto;
	}

	public void setIdDepto(Long idDepto) {
		this.idDepto = idDepto;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

}
