package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetallePl generated by hbm2java
 */
@Entity
@Table(name = "detalle_pl")
public class DetallePl implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "citipo_pl")
	private String tipoPl;
	
	@Column(name = "num_pl")
	private String numPl;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "tipo")
	private String tipo;
	
	@Column(name = "num_dcto")
	private String numDcto;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "descripcion")
	private String descripcion;
	
	@Column(name = "anio")
	private String anio;
	
	@Column(name = "nopieza")
	private String noPieza;
	
	@Column(name = "debe")
	private Float debe;
	
	@Column(name = "registro")
	private String registro;
	
	@Column(name = "item")
	private Long item;
	
	@Column(name = "estanteria")
	private String estanteria;
	
	@Column(name = "ubicacion")
	private String ubicacion;
	
	@Column(name = "fila")
	private String fila;
	
	@Column(name = "motor")
	private String motor;
	
	@Column(name = "chasis")
	private String chasis;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;
	
	@Column(name = "precio")
	private Float precio;
	
	@Column(name = "preciomin")
	private Float precioMin;
	
	@Column(name = "preciomax")
	private Float precioMax;
	
	@Column(name = "razonnoventa")
	private String razonNoVenta;

	public DetallePl() {
	}

	public DetallePl(Long cia, String numPl) {
		this.cia = cia;
		this.numPl = numPl;
	}

	public DetallePl(Long cia, String tipoPl, String numPl, Date fecha, String tipo, String numDcto, String codArt,
			String descripcion, String anio, String noPieza, Float debe, String registro, Long item, String estanteria,
			String ubicacion, String fila, String motor, String chasis, Character statReg, String usuario,
			Date fechaIngreso, Float precio, Float precioMin, Float precioMax, String razonNoVenta) {
		this.cia = cia;
		this.tipoPl = tipoPl;
		this.numPl = numPl;
		this.fecha = fecha;
		this.tipo = tipo;
		this.numDcto = numDcto;
		this.codArt = codArt;
		this.descripcion = descripcion;
		this.anio = anio;
		this.noPieza = noPieza;
		this.debe = debe;
		this.registro = registro;
		this.item = item;
		this.estanteria = estanteria;
		this.ubicacion = ubicacion;
		this.fila = fila;
		this.motor = motor;
		this.chasis = chasis;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
		this.precio = precio;
		this.precioMin = precioMin;
		this.precioMax = precioMax;
		this.razonNoVenta = razonNoVenta;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getTipoPl() {
		return this.tipoPl;
	}

	public void setTipoPl(String tipoPl) {
		this.tipoPl = tipoPl;
	}

	public String getNumPl() {
		return this.numPl;
	}

	public void setNumPl(String numPl) {
		this.numPl = numPl;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getNumDcto() {
		return this.numDcto;
	}

	public void setNumDcto(String numDcto) {
		this.numDcto = numDcto;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getAnio() {
		return this.anio;
	}

	public void setAnio(String anio) {
		this.anio = anio;
	}

	public String getNoPieza() {
		return this.noPieza;
	}

	public void setNoPieza(String noPieza) {
		this.noPieza = noPieza;
	}

	public Float getDebe() {
		return this.debe;
	}

	public void setDebe(Float debe) {
		this.debe = debe;
	}

	public String getRegistro() {
		return this.registro;
	}

	public void setRegistro(String registro) {
		this.registro = registro;
	}

	public Long getItem() {
		return this.item;
	}

	public void setItem(Long item) {
		this.item = item;
	}

	public String getEstanteria() {
		return this.estanteria;
	}

	public void setEstanteria(String estanteria) {
		this.estanteria = estanteria;
	}

	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public String getFila() {
		return this.fila;
	}

	public void setFila(String fila) {
		this.fila = fila;
	}

	public String getMotor() {
		return this.motor;
	}

	public void setMotor(String motor) {
		this.motor = motor;
	}

	public String getChasis() {
		return this.chasis;
	}

	public void setChasis(String chasis) {
		this.chasis = chasis;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	public Float getPrecioMin() {
		return this.precioMin;
	}

	public void setPrecioMin(Float precioMin) {
		this.precioMin = precioMin;
	}

	public Float getPrecioMax() {
		return this.precioMax;
	}

	public void setPrecioMax(Float precioMax) {
		this.precioMax = precioMax;
	}

	public String getRazonNoVenta() {
		return this.razonNoVenta;
	}

	public void setRazonNoVenta(String razonNoVenta) {
		this.razonNoVenta = razonNoVenta;
	}

}
