package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetVarios generated by hbm2java
 */
@Entity
@Table(name = "det_varios")
public class DetVarios implements java.io.Serializable {

	@Id
	@Column(name = "id_det_varios")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idDetVarios;
	
	@Column(name = "num_dcto")
	private String numDcto;
	
	@Column(name = "item")
	private Float item;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "descripcion")
	private String descripcion;
	
	@Column(name = "debe")
	private Float debe;
	
	@Column(name = "pu")
	private Float pu;
	
	@Column(name = "valor")
	private Float valor;

	public DetVarios() {
	}

	public DetVarios(String numDcto, Float item, String codArt, String descripcion, Float debe, Float pu, Float valor) {
		this.numDcto = numDcto;
		this.item = item;
		this.codArt = codArt;
		this.descripcion = descripcion;
		this.debe = debe;
		this.pu = pu;
		this.valor = valor;
	}

	public Long getIdDetVarios() {
		return this.idDetVarios;
	}

	public void setIdDetVarios(Long idDetVarios) {
		this.idDetVarios = idDetVarios;
	}

	public String getNumDcto() {
		return this.numDcto;
	}

	public void setNumDcto(String numDcto) {
		this.numDcto = numDcto;
	}

	public Float getItem() {
		return this.item;
	}

	public void setItem(Float item) {
		this.item = item;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Float getDebe() {
		return this.debe;
	}

	public void setDebe(Float debe) {
		this.debe = debe;
	}

	public Float getPu() {
		return this.pu;
	}

	public void setPu(Float pu) {
		this.pu = pu;
	}

	public Float getValor() {
		return this.valor;
	}

	public void setValor(Float valor) {
		this.valor = valor;
	}

}
