package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DevolucionPedido generated by hbm2java
 */
@Entity
@Table(name = "devolucion_pedido")
public class DevolucionPedido implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "tipo_dev")
	private String tipoDev;
	
	@Column(name = "numero_dev")
	private String numeroDev;
	
	@Column(name = "fecha_dev")
	private Date fechaDev;
	
	@Column(name = "tipo")
	private String tipo;
	
	@Column(name = "numero")
	private String numero;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public DevolucionPedido() {
	}

	public DevolucionPedido(Long cia) {
		this.cia = cia;
	}

	public DevolucionPedido(Long cia, String tipoDev, String numeroDev, Date fechaDev, String tipo, String numero,
			Date fecha, Character statReg, String usuario, Date fechaIngreso) {
		this.cia = cia;
		this.tipoDev = tipoDev;
		this.numeroDev = numeroDev;
		this.fechaDev = fechaDev;
		this.tipo = tipo;
		this.numero = numero;
		this.fecha = fecha;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getTipoDev() {
		return this.tipoDev;
	}

	public void setTipoDev(String tipoDev) {
		this.tipoDev = tipoDev;
	}

	public String getNumeroDev() {
		return this.numeroDev;
	}

	public void setNumeroDev(String numeroDev) {
		this.numeroDev = numeroDev;
	}

	public Date getFechaDev() {
		return this.fechaDev;
	}

	public void setFechaDev(Date fechaDev) {
		this.fechaDev = fechaDev;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
