package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Dolar generated by hbm2java
 */
@Entity
@Table(name = "dolar")
public class Dolar implements java.io.Serializable {

	@Id
	@Column(name = "id_dolar")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idDolar;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "guacompra")
	private Float guaCompra;
	
	@Column(name = "guaventa")
	private Float guaVenta;
	
	@Column(name = "indcompra")
	private Float indCompra;
	
	@Column(name = "indventa")
	private Float indVenta;
	
	@Column(name = "agrocompra")
	private Float agroCompra;
	
	@Column(name = "agroventa")
	private Float agroVenta;
	
	@Column(name = "tasa")
	private Float tasa;
	
	@Column(name = "dia")
	private String dia;
	
	@Column(name = "campo")
	private String campo;

	public Dolar() {
	}

	public Dolar(Date fecha) {
		this.fecha = fecha;
	}

	public Dolar(Date fecha, Float guaCompra, Float guaVenta, Float indCompra, Float indVenta, Float agroCompra,
			Float agroVenta, Float tasa, String dia, String campo) {
		this.fecha = fecha;
		this.guaCompra = guaCompra;
		this.guaVenta = guaVenta;
		this.indCompra = indCompra;
		this.indVenta = indVenta;
		this.agroCompra = agroCompra;
		this.agroVenta = agroVenta;
		this.tasa = tasa;
		this.dia = dia;
		this.campo = campo;
	}

	public Long getIdDolar() {
		return this.idDolar;
	}

	public void setIdDolar(Long idDolar) {
		this.idDolar = idDolar;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Float getGuaCompra() {
		return this.guaCompra;
	}

	public void setGuaCompra(Float guaCompra) {
		this.guaCompra = guaCompra;
	}

	public Float getGuaVenta() {
		return this.guaVenta;
	}

	public void setGuaVenta(Float guaVenta) {
		this.guaVenta = guaVenta;
	}

	public Float getIndCompra() {
		return this.indCompra;
	}

	public void setIndCompra(Float indCompra) {
		this.indCompra = indCompra;
	}

	public Float getIndVenta() {
		return this.indVenta;
	}

	public void setIndVenta(Float indVenta) {
		this.indVenta = indVenta;
	}

	public Float getAgroCompra() {
		return this.agroCompra;
	}

	public void setAgroCompra(Float agroCompra) {
		this.agroCompra = agroCompra;
	}

	public Float getAgroVenta() {
		return this.agroVenta;
	}

	public void setAgroVenta(Float agroVenta) {
		this.agroVenta = agroVenta;
	}

	public Float getTasa() {
		return this.tasa;
	}

	public void setTasa(Float tasa) {
		this.tasa = tasa;
	}

	public String getDia() {
		return this.dia;
	}

	public void setDia(String dia) {
		this.dia = dia;
	}

	public String getCampo() {
		return this.campo;
	}

	public void setCampo(String campo) {
		this.campo = campo;
	}

}
