package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Entregamerc generated by hbm2java
 */
@Entity
@Table(name = "entregamerc")
public class EntregaMerc implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "tipo")
	private String tipo;
	
	@Column(name = "bodega")
	private String bodega;
	
	@Column(name = "numero")
	private String numero;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;
	
	@Column(name = "usuario_entrega")
	private String usuarioEntrega;
	
	@Column(name = "fecha_entrega")
	private Date fechaEntrega;

	public EntregaMerc() {
	}

	public EntregaMerc(Long cia) {
		this.cia = cia;
	}

	public EntregaMerc(Long cia, String tipo, String bodega, String numero, Date fecha, Character statReg,
			String usuario, Date fechaIngreso, String usuarioEntrega, Date fechaEntrega) {
		this.cia = cia;
		this.tipo = tipo;
		this.bodega = bodega;
		this.numero = numero;
		this.fecha = fecha;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
		this.usuarioEntrega = usuarioEntrega;
		this.fechaEntrega = fechaEntrega;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getBodega() {
		return this.bodega;
	}

	public void setBodega(String bodega) {
		this.bodega = bodega;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getUsuarioEntrega() {
		return this.usuarioEntrega;
	}

	public void setUsuarioEntrega(String usuarioEntrega) {
		this.usuarioEntrega = usuarioEntrega;
	}

	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

}
