package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado")
public class Estado implements java.io.Serializable {

	@Id
	@Column(name = "id_estado")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idEstado;
	
	@Column(name = "nit")
	private String nit;
	
	@Column(name = "nombre1")
	private String nombre1;
	
	@Column(name = "direccion")
	private String direccion;
	
	@Column(name = "telefonos")
	private String telefonos;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "numero")
	private String numero;
	
	@Column(name = "valor_fac")
	private Float valorFac;
	
	@Column(name = "f_ven_fac")
	private Date FVenFac;
	
	@Column(name = "dias_vencidos")
	private Float diasVencidos;
	
	@Column(name = "tipo")
	private Character tipo;
	
	@Column(name = "fecha_rec")
	private Date fechaRec;
	
	@Column(name = "recibo")
	private String recibo;
	
	@Column(name = "valorec")
	private Float valorEc;
	
	@Column(name = "saldofac")
	private Float saldoFac;

	public Estado() {
	}

	public Estado(String nit, String nombre1, String direccion, String telefonos, Date fecha, String numero,
			Float valorFac, Date FVenFac, Float diasVencidos, Character tipo, Date fechaRec, String recibo,
			Float valorEc, Float saldoFac) {
		this.nit = nit;
		this.nombre1 = nombre1;
		this.direccion = direccion;
		this.telefonos = telefonos;
		this.fecha = fecha;
		this.numero = numero;
		this.valorFac = valorFac;
		this.FVenFac = FVenFac;
		this.diasVencidos = diasVencidos;
		this.tipo = tipo;
		this.fechaRec = fechaRec;
		this.recibo = recibo;
		this.valorEc = valorEc;
		this.saldoFac = saldoFac;
	}

	public Long getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(Long idEstado) {
		this.idEstado = idEstado;
	}

	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	public String getNombre1() {
		return this.nombre1;
	}

	public void setNombre1(String nombre1) {
		this.nombre1 = nombre1;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefonos() {
		return this.telefonos;
	}

	public void setTelefonos(String telefonos) {
		this.telefonos = telefonos;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public Float getValorFac() {
		return this.valorFac;
	}

	public void setValorFac(Float valorFac) {
		this.valorFac = valorFac;
	}

	public Date getFVenFac() {
		return this.FVenFac;
	}

	public void setFVenFac(Date FVenFac) {
		this.FVenFac = FVenFac;
	}

	public Float getDiasVencidos() {
		return this.diasVencidos;
	}

	public void setDiasVencidos(Float diasVencidos) {
		this.diasVencidos = diasVencidos;
	}

	public Character getTipo() {
		return this.tipo;
	}

	public void setTipo(Character tipo) {
		this.tipo = tipo;
	}

	public Date getFechaRec() {
		return this.fechaRec;
	}

	public void setFechaRec(Date fechaRec) {
		this.fechaRec = fechaRec;
	}

	public String getRecibo() {
		return this.recibo;
	}

	public void setRecibo(String recibo) {
		this.recibo = recibo;
	}

	public Float getValorEc() {
		return this.valorEc;
	}

	public void setValorEc(Float valorEc) {
		this.valorEc = valorEc;
	}

	public Float getSaldoFac() {
		return this.saldoFac;
	}

	public void setSaldoFac(Float saldoFac) {
		this.saldoFac = saldoFac;
	}

}
