package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fisico generated by hbm2java
 */
@Entity
@Table(name = "fisico")
public class Fisico implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "bodega")
	private String bodega;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "descripcion")
	private String descripcion;
	
	@Column(name = "unidades")
	private float unidades;
	
	@Column(name = "fisico")
	private float fisico;

	public Fisico() {
	}

	public Fisico(Long cia, String bodega, Date fecha, String codArt, String descripcion, float unidades,
			float fisico) {
		this.cia = cia;
		this.bodega = bodega;
		this.fecha = fecha;
		this.codArt = codArt;
		this.descripcion = descripcion;
		this.unidades = unidades;
		this.fisico = fisico;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getBodega() {
		return this.bodega;
	}

	public void setBodega(String bodega) {
		this.bodega = bodega;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public float getUnidades() {
		return this.unidades;
	}

	public void setUnidades(float unidades) {
		this.unidades = unidades;
	}

	public float getFisico() {
		return this.fisico;
	}

	public void setFisico(float fisico) {
		this.fisico = fisico;
	}

}
