package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Maestro generated by hbm2java
 */
@Entity
@Table(name = "maestro")
public class Maestro implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "nombre")
	private String nombre;
	
	@Column(name = "minimo")
	private Float minimo;
	
	@Column(name = "maximo")
	private Float maximo;
	
	@Column(name = "capacidad")
	private String capacidad;
	
	@Column(name = "marca")
	private String marca;
	
	@Column(name = "medida")
	private String medida;
	
	@Column(name = "modulo")
	private String modulo;
	
	@Column(name = "parte")
	private String parte;
	
	@Column(name = "serie")
	private boolean serie;
	
	@Column(name = "precio_01")
	private Float precio01;
	
	@Column(name = "precio_02")
	private Float precio02;
	
	@Column(name = "precio_03")
	private Float precio03;
	
	@Column(name = "precio_04")
	private Float precio04;
	
	@Column(name = "precio_05")
	private Float precio05;
	
	@Column(name = "precio_06")
	private Float precio06;
	
	@Column(name = "cos_depre")
	private Float cosDepre;
	
	@Column(name = "costo_quet")
	private Float costoQuet;
	
	@Column(name = "costo_dola")
	private float costoDola;
	
	@Column(name = "costo_cif")
	private Float costoCif;
	
	@Column(name = "gatos")
	private Float gastos;
	
	@Column(name = "activo")
	private boolean activo;
	
	@Column(name = "importado")
	private boolean importado;
	
	@Column(name = "costo_dolar")
	private Float costoDolar;
	
	@Column(name = "existe")
	private Float existe;
	
	@Column(name = "provee")
	private String provee;
	
	@Column(name = "saldoinicial")
	private Float saldoInicial;
	
	@Column(name = "entradas")
	private Float entradas;
	
	@Column(name = "salidas")
	private Float salidas;
	
	@Column(name = "costo_q_a")
	private Float costoQA;
	
	@Column(name = "costo_d_a")
	private Float costoDA;
	
	@Column(name = "ul_costo_q")
	private Float ulCostoQ;
	
	@Column(name = "ul_costo_d")
	private Float ulCostoD;
	
	@Column(name = "tasa")
	private Float tasa;
	
	@Column(name = "ul_tasa")
	private Float ulTasa;

	public Maestro() {
	}

	public Maestro(Long cia, String codArt, String nombre, boolean serie, float costoDola, boolean activo,
			boolean importado) {
		this.cia = cia;
		this.codArt = codArt;
		this.nombre = nombre;
		this.serie = serie;
		this.costoDola = costoDola;
		this.activo = activo;
		this.importado = importado;
	}

	public Maestro(Long cia, String codArt, String nombre, Float minimo, Float maximo, String capacidad, String marca,
			String medida, String modulo, String parte, boolean serie, Float precio01, Float precio02, Float precio03,
			Float precio04, Float precio05, Float precio06, Float cosDepre, Float costoQuet, float costoDola,
			Float costoCif, Float gastos, boolean activo, boolean importado, Float costoDolar, Float existe,
			String provee, Float saldoInicial, Float entradas, Float salidas, Float costoQA, Float costoDA,
			Float ulCostoQ, Float ulCostoD, Float tasa, Float ulTasa) {
		this.cia = cia;
		this.codArt = codArt;
		this.nombre = nombre;
		this.minimo = minimo;
		this.maximo = maximo;
		this.capacidad = capacidad;
		this.marca = marca;
		this.medida = medida;
		this.modulo = modulo;
		this.parte = parte;
		this.serie = serie;
		this.precio01 = precio01;
		this.precio02 = precio02;
		this.precio03 = precio03;
		this.precio04 = precio04;
		this.precio05 = precio05;
		this.precio06 = precio06;
		this.cosDepre = cosDepre;
		this.costoQuet = costoQuet;
		this.costoDola = costoDola;
		this.costoCif = costoCif;
		this.gastos = gastos;
		this.activo = activo;
		this.importado = importado;
		this.costoDolar = costoDolar;
		this.existe = existe;
		this.provee = provee;
		this.saldoInicial = saldoInicial;
		this.entradas = entradas;
		this.salidas = salidas;
		this.costoQA = costoQA;
		this.costoDA = costoDA;
		this.ulCostoQ = ulCostoQ;
		this.ulCostoD = ulCostoD;
		this.tasa = tasa;
		this.ulTasa = ulTasa;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Float getMinimo() {
		return this.minimo;
	}

	public void setMinimo(Float minimo) {
		this.minimo = minimo;
	}

	public Float getMaximo() {
		return this.maximo;
	}

	public void setMaximo(Float maximo) {
		this.maximo = maximo;
	}

	public String getCapacidad() {
		return this.capacidad;
	}

	public void setCapacidad(String capacidad) {
		this.capacidad = capacidad;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getMedida() {
		return this.medida;
	}

	public void setMedida(String medida) {
		this.medida = medida;
	}

	public String getModulo() {
		return this.modulo;
	}

	public void setModulo(String modulo) {
		this.modulo = modulo;
	}

	public String getParte() {
		return this.parte;
	}

	public void setParte(String parte) {
		this.parte = parte;
	}

	public boolean isSerie() {
		return this.serie;
	}

	public void setSerie(boolean serie) {
		this.serie = serie;
	}

	public Float getPrecio01() {
		return this.precio01;
	}

	public void setPrecio01(Float precio01) {
		this.precio01 = precio01;
	}

	public Float getPrecio02() {
		return this.precio02;
	}

	public void setPrecio02(Float precio02) {
		this.precio02 = precio02;
	}

	public Float getPrecio03() {
		return this.precio03;
	}

	public void setPrecio03(Float precio03) {
		this.precio03 = precio03;
	}

	public Float getPrecio04() {
		return this.precio04;
	}

	public void setPrecio04(Float precio04) {
		this.precio04 = precio04;
	}

	public Float getPrecio05() {
		return this.precio05;
	}

	public void setPrecio05(Float precio05) {
		this.precio05 = precio05;
	}

	public Float getPrecio06() {
		return this.precio06;
	}

	public void setPrecio06(Float precio06) {
		this.precio06 = precio06;
	}

	public Float getCosDepre() {
		return this.cosDepre;
	}

	public void setCosDepre(Float cosDepre) {
		this.cosDepre = cosDepre;
	}

	public Float getCostoQuet() {
		return this.costoQuet;
	}

	public void setCostoQuet(Float costoQuet) {
		this.costoQuet = costoQuet;
	}

	public float getCostoDola() {
		return this.costoDola;
	}

	public void setCostoDola(float costoDola) {
		this.costoDola = costoDola;
	}

	public Float getCostoCif() {
		return this.costoCif;
	}

	public void setCostoCif(Float costoCif) {
		this.costoCif = costoCif;
	}

	public Float getGastos() {
		return this.gastos;
	}

	public void setGastos(Float gastos) {
		this.gastos = gastos;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public boolean isImportado() {
		return this.importado;
	}

	public void setImportado(boolean importado) {
		this.importado = importado;
	}

	public Float getCostoDolar() {
		return this.costoDolar;
	}

	public void setCostoDolar(Float costoDolar) {
		this.costoDolar = costoDolar;
	}

	public Float getExiste() {
		return this.existe;
	}

	public void setExiste(Float existe) {
		this.existe = existe;
	}

	public String getProvee() {
		return this.provee;
	}

	public void setProvee(String provee) {
		this.provee = provee;
	}

	public Float getSaldoInicial() {
		return this.saldoInicial;
	}

	public void setSaldoInicial(Float saldoInicial) {
		this.saldoInicial = saldoInicial;
	}

	public Float getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Float entradas) {
		this.entradas = entradas;
	}

	public Float getSalidas() {
		return this.salidas;
	}

	public void setSalidas(Float salidas) {
		this.salidas = salidas;
	}

	public Float getCostoQA() {
		return this.costoQA;
	}

	public void setCostoQA(Float costoQA) {
		this.costoQA = costoQA;
	}

	public Float getCostoDA() {
		return this.costoDA;
	}

	public void setCostoDA(Float costoDA) {
		this.costoDA = costoDA;
	}

	public Float getUlCostoQ() {
		return this.ulCostoQ;
	}

	public void setUlCostoQ(Float ulCostoQ) {
		this.ulCostoQ = ulCostoQ;
	}

	public Float getUlCostoD() {
		return this.ulCostoD;
	}

	public void setUlCostoD(Float ulCostoD) {
		this.ulCostoD = ulCostoD;
	}

	public Float getTasa() {
		return this.tasa;
	}

	public void setTasa(Float tasa) {
		this.tasa = tasa;
	}

	public Float getUlTasa() {
		return this.ulTasa;
	}

	public void setUlTasa(Float ulTasa) {
		this.ulTasa = ulTasa;
	}

}
