package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Mdetalle generated by hbm2java
 */
@Entity
@Table(name = "mdetalle")
public class MDetalle implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "bodega")
	private String bodega;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "debe")
	private Float debe;
	
	@Column(name = "haber")
	private Float haber;
	
	@Column(name = "d_q")
	private Float DQ;
	
	@Column(name = "h_q")
	private Float HQ;
	
	@Column(name = "minimo")
	private Float minimo;
	
	@Column(name = "maximo")
	private Float maximo;
	
	@Column(name = "fisico")
	private Float fisico;

	public MDetalle() {
	}

	public MDetalle(Long cia, String bodega, String codArt) {
		this.cia = cia;
		this.bodega = bodega;
		this.codArt = codArt;
	}

	public MDetalle(Long cia, String bodega, String codArt, Float debe, Float haber, Float DQ, Float HQ, Float minimo,
			Float maximo, Float fisico) {
		this.cia = cia;
		this.bodega = bodega;
		this.codArt = codArt;
		this.debe = debe;
		this.haber = haber;
		this.DQ = DQ;
		this.HQ = HQ;
		this.minimo = minimo;
		this.maximo = maximo;
		this.fisico = fisico;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getBodega() {
		return this.bodega;
	}

	public void setBodega(String bodega) {
		this.bodega = bodega;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public Float getDebe() {
		return this.debe;
	}

	public void setDebe(Float debe) {
		this.debe = debe;
	}

	public Float getHaber() {
		return this.haber;
	}

	public void setHaber(Float haber) {
		this.haber = haber;
	}

	public Float getDQ() {
		return this.DQ;
	}

	public void setDQ(Float DQ) {
		this.DQ = DQ;
	}

	public Float getHQ() {
		return this.HQ;
	}

	public void setHQ(Float HQ) {
		this.HQ = HQ;
	}

	public Float getMinimo() {
		return this.minimo;
	}

	public void setMinimo(Float minimo) {
		this.minimo = minimo;
	}

	public Float getMaximo() {
		return this.maximo;
	}

	public void setMaximo(Float maximo) {
		this.maximo = maximo;
	}

	public Float getFisico() {
		return this.fisico;
	}

	public void setFisico(Float fisico) {
		this.fisico = fisico;
	}

}
