package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MesL generated by hbm2java
 */
@Entity
@Table(name = "mes_l")
public class MesL implements java.io.Serializable {

	@Id
	@Column(name = "id_mes_l")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idMesL;
	
	@Column(name = "nombre")
	private String nombre;
	
	@Column(name = "no")
	private float no;

	public MesL() {
	}

	public MesL(String nombre, float no) {
		this.nombre = nombre;
		this.no = no;
	}

	public Long getIdMesL() {
		return this.idMesL;
	}

	public void setIdMesL(Long idMesL) {
		this.idMesL = idMesL;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public float getNo() {
		return this.no;
	}

	public void setNo(float no) {
		this.no = no;
	}

}
