package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Modulos generated by hbm2java
 */
@Entity
@Table(name = "modulos")
public class Modulos implements java.io.Serializable {

	@Id
	@Column(name = "id_modulos")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idModulos;
	
	@Column(name = "codigo")
	private String codigo;
	
	@Column(name = "nombre")
	private String nombre;

	public Modulos() {
	}

	public Modulos(String codigo, String nombre) {
		this.codigo = codigo;
		this.nombre = nombre;
	}

	public Long getIdModulos() {
		return this.idModulos;
	}

	public void setIdModulos(Long idModulos) {
		this.idModulos = idModulos;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
