package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Provee generated by hbm2java
 */
@Entity
@Table(name = "provee")
public class Provee implements java.io.Serializable {

	@Id
	@Column(name = "id_provee")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idProvee;
	
	@Column(name = "codigo")
	private String codigo;
	
	@Column(name = "nombre")
	private String nombre;
	
	@Column(name = "tel")
	private String tel;
	
	@Column(name = "fax")
	private String fax;
	
	@Column(name = "direccion")
	private String direccion;
	
	@Column(name = "localexter")
	private float localExter;
	
	@Column(name = "nit")
	private String nit;
	
	@Column(name = "dcredito")
	private Float dCredito;

	public Provee() {
	}

	public Provee(String codigo, String nombre, String tel, String fax, String direccion, float localExter) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.tel = tel;
		this.fax = fax;
		this.direccion = direccion;
		this.localExter = localExter;
	}

	public Provee(String codigo, String nombre, String tel, String fax, String direccion, float localExter, String nit,
			Float dcredito) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.tel = tel;
		this.fax = fax;
		this.direccion = direccion;
		this.localExter = localExter;
		this.nit = nit;
		this.dCredito = dCredito;
	}

	public Long getIdProvee() {
		return this.idProvee;
	}

	public void setIdProvee(Long idProvee) {
		this.idProvee = idProvee;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public float getLocalExter() {
		return this.localExter;
	}

	public void setLocalExter(float localExter) {
		this.localExter = localExter;
	}

	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	public Float getDCredito() {
		return this.dCredito;
	}

	public void setDCredito(Float dCredito) {
		this.dCredito = dCredito;
	}

}
