package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Recibos generated by hbm2java
 */
@Entity
@Table(name = "recibos")
public class Recibos implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "codigo")
	private String codigo;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "numero")
	private String numero;
	
	@Column(name = "nombrefa")
	private String nombreFa;
	
	@Column(name = "dirfa")
	private String dirFa;
	
	@Column(name = "vendedor")
	private String vendedor;
	
	@Column(name = "tipo")
	private String tipo;
	
	@Column(name = "debe")
	private Float debe;
	
	@Column(name = "haber")
	private Float haber;
	
	@Column(name = "mes")
	private String mes;
	
	@Column(name = "year")
	private String year;
	
	@Column(name = "anulado")
	private boolean anulado;
	
	@Column(name = "efectivo")
	private Float efectivo;
	
	@Column(name = "cheque")
	private Float cheque;
	
	@Column(name = "ncheque")
	private String nCheque;
	
	@Column(name = "credito")
	private Float credito;
	
	@Column(name = "tarjeta")
	private Float tarjeta;
	
	@Column(name = "otros")
	private Float otros;
	
	@Column(name = "banco")
	private String banco;
	
	@Column(name = "cuenta")
	private String cuenta;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public Recibos() {
	}

	public Recibos(Long cia, String numero, boolean anulado) {
		this.cia = cia;
		this.numero = numero;
		this.anulado = anulado;
	}

	public Recibos(Long cia, String codigo, Date fecha, String numero, String nombreFa, String dirFa, String vendedor,
			String tipo, Float debe, Float haber, String mes, String year, boolean anulado, Float efectivo,
			Float cheque, String nCheque, Float credito, Float tarjeta, Float otros, String banco, String cuenta,
			Character statReg, String usuario, Date fechaIngreso) {
		this.cia = cia;
		this.codigo = codigo;
		this.fecha = fecha;
		this.numero = numero;
		this.nombreFa = nombreFa;
		this.dirFa = dirFa;
		this.vendedor = vendedor;
		this.tipo = tipo;
		this.debe = debe;
		this.haber = haber;
		this.mes = mes;
		this.year = year;
		this.anulado = anulado;
		this.efectivo = efectivo;
		this.cheque = cheque;
		this.nCheque = nCheque;
		this.credito = credito;
		this.tarjeta = tarjeta;
		this.otros = otros;
		this.banco = banco;
		this.cuenta = cuenta;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getNombreFa() {
		return this.nombreFa;
	}

	public void setNombreFa(String nombreFa) {
		this.nombreFa = nombreFa;
	}

	public String getDirFa() {
		return this.dirFa;
	}

	public void setDirFa(String dirFa) {
		this.dirFa = dirFa;
	}

	public String getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(String vendedor) {
		this.vendedor = vendedor;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Float getDebe() {
		return this.debe;
	}

	public void setDebe(Float debe) {
		this.debe = debe;
	}

	public Float getHaber() {
		return this.haber;
	}

	public void setHaber(Float haber) {
		this.haber = haber;
	}

	public String getMes() {
		return this.mes;
	}

	public void setMes(String mes) {
		this.mes = mes;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public boolean isAnulado() {
		return this.anulado;
	}

	public void setAnulado(boolean anulado) {
		this.anulado = anulado;
	}

	public Float getEfectivo() {
		return this.efectivo;
	}

	public void setEfectivo(Float efectivo) {
		this.efectivo = efectivo;
	}

	public Float getCheque() {
		return this.cheque;
	}

	public void setCheque(Float cheque) {
		this.cheque = cheque;
	}

	public String getNCheque() {
		return this.nCheque;
	}

	public void setNCheque(String nCheque) {
		this.nCheque = nCheque;
	}

	public Float getCredito() {
		return this.credito;
	}

	public void setCredito(Float credito) {
		this.credito = credito;
	}

	public Float getTarjeta() {
		return this.tarjeta;
	}

	public void setTarjeta(Float tarjeta) {
		this.tarjeta = tarjeta;
	}

	public Float getOtros() {
		return this.otros;
	}

	public void setOtros(Float otros) {
		this.otros = otros;
	}

	public String getBanco() {
		return this.banco;
	}

	public void setBanco(String banco) {
		this.banco = banco;
	}

	public String getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(String cuenta) {
		this.cuenta = cuenta;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
