package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Tarjeta generated by hbm2java
 */
@Entity
@Table(name = "tarjeta")
public class Tarjeta implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "nitcliente")
	private String nitCliente;
	
	@Column(name = "factura")
	private String factura;
	
	@Column(name = "emisor")
	private String emisor;
	
	@Column(name = "numero")
	private String numero;
	
	@Column(name = "vence")
	private String vence;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "telefono")
	private String telefono;
	
	@Column(name = "autorizacion")
	private String autorizacion;
	
	@Column(name = "valor")
	private Float valor;
	
	@Column(name = "observaciones")
	private String observaciones;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public Tarjeta() {
	}

	public Tarjeta(Long cia) {
		this.cia = cia;
	}

	public Tarjeta(Long cia, String nitCliente, String factura, String emisor, String numero, String vence, Date fecha,
			String telefono, String autorizacion, Float valor, String observaciones, Character statReg, String usuario,
			Date fechaIngreso) {
		this.cia = cia;
		this.nitCliente = nitCliente;
		this.factura = factura;
		this.emisor = emisor;
		this.numero = numero;
		this.vence = vence;
		this.fecha = fecha;
		this.telefono = telefono;
		this.autorizacion = autorizacion;
		this.valor = valor;
		this.observaciones = observaciones;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getNitCliente() {
		return this.nitCliente;
	}

	public void setNitCliente(String nitCliente) {
		this.nitCliente = nitCliente;
	}

	public String getFactura() {
		return this.factura;
	}

	public void setFactura(String factura) {
		this.factura = factura;
	}

	public String getEmisor() {
		return this.emisor;
	}

	public void setEmisor(String emisor) {
		this.emisor = emisor;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getVence() {
		return this.vence;
	}

	public void setVence(String vence) {
		this.vence = vence;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getAutorizacion() {
		return this.autorizacion;
	}

	public void setAutorizacion(String autorizacion) {
		this.autorizacion = autorizacion;
	}

	public Float getValor() {
		return this.valor;
	}

	public void setValor(Float valor) {
		this.valor = valor;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
