package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Vendedor generated by hbm2java
 */
@Entity
@Table(name = "vendedor")
public class Vendedor implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "codigo")
	private String codigo;
	
	@Column(name = "nombre")
	private String nombre;
	
	@Column(name = "comision")
	private Float comision;
	
	@Column(name = "cotizacion")
	private Float cotizacion;
	
	@Column(name = "notaentrega")
	private Float notaEntrega;
	
	@Column(name = "facturascontado")
	private Float facturasContado;
	
	@Column(name = "facturacredito")
	private Float facturaCredito;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public Vendedor() {
	}

	public Vendedor(Long cia) {
		this.cia = cia;
	}

	public Vendedor(Long cia, String codigo, String nombre, Float comision, Float cotizacion, Float notaEntrega,
			Float facturasContado, Float facturaCredito, Character statReg, String usuario, Date fechaIngreso) {
		this.cia = cia;
		this.codigo = codigo;
		this.nombre = nombre;
		this.comision = comision;
		this.cotizacion = cotizacion;
		this.notaEntrega = notaEntrega;
		this.facturasContado = facturasContado;
		this.facturaCredito = facturaCredito;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Float getComision() {
		return this.comision;
	}

	public void setComision(Float comision) {
		this.comision = comision;
	}

	public Float getCotizacion() {
		return this.cotizacion;
	}

	public void setCotizacion(Float cotizacion) {
		this.cotizacion = cotizacion;
	}

	public Float getNotaEntrega() {
		return this.notaEntrega;
	}

	public void setNotaEntrega(Float notaEntrega) {
		this.notaEntrega = notaEntrega;
	}

	public Float getFacturasContado() {
		return this.facturasContado;
	}

	public void setFacturasContado(Float facturasContado) {
		this.facturasContado = facturasContado;
	}

	public Float getFacturaCredito() {
		return this.facturaCredito;
	}

	public void setFacturaCredito(Float facturaCredito) {
		this.facturaCredito = facturaCredito;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
