package com.scm.gsoft.domain.cxc;
// Generated 26/08/2018 01:38:39 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ventas generated by hbm2java
 */
@Entity
@Table(name = "ventas")
public class Ventas implements java.io.Serializable {

	@Id
	@Column(name = "id_ventas")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idVentas;
	
	@Column(name = "cod_art")
	private String codArt;

	public Ventas() {
	}

	public Ventas(String codArt) {
		this.codArt = codArt;
	}

	public Long getIdVentas() {
		return this.idVentas;
	}

	public void setIdVentas(Long idVentas) {
		this.idVentas = idVentas;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

}
