package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ArtH generated by hbm2java
 */
@Entity
@Table(name = "art_H")
public class ArtH implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "transa")
	private Character transa;
	
	@Column(name = "tipo")
	private String tipo;
	
	@Column(name = "bodega")
	private String bodega;
	
	@Column(name = "numero")
	private String numero;
	
	@Column(name = "descri")
	private String descri;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "concepto")
	private String concepto;
	
	@Column(name = "proveedor")
	private String proveedor;
	
	@Column(name = "factura")
	private String factura;
	
	@Column(name = "polisa")
	private String polisa;
	
	@Column(name = "campo")
	private String campo;
	
	@Column(name = "bodega2")
	private String bodega2;
	
	@Column(name = "tipot")
	private String tipoT;
	
	@Column(name = "vendedor")
	private String vendedor;
	
	@Column(name = "bodeguero")
	private String bodeguero;
	
	@Column(name = "requisicion")
	private String requisicion;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;
	
	@Column(name = "timestamp_column")
	private Character timestampColumn;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "descripcion")
	private String descripcion;
	
	@Column(name = "cantidad")
	private Float cantidad;
	
	@Column(name = "producida")
	private Float producida;

	public ArtH() {
	}

	public ArtH(Character transa, String tipo, String bodega, String numero, String descri, Date fecha, String concepto,
			String proveedor, String factura, String polisa, String campo, String bodega2, String tipoT,
			String vendedor, String bodeguero, String requisicion, Character statReg, String usuario, Date fechaIngreso,
			Character timestampColumn, String codArt, String descripcion, Float cantidad, Float producida) {
		this.transa = transa;
		this.tipo = tipo;
		this.bodega = bodega;
		this.numero = numero;
		this.descri = descri;
		this.fecha = fecha;
		this.concepto = concepto;
		this.proveedor = proveedor;
		this.factura = factura;
		this.polisa = polisa;
		this.campo = campo;
		this.bodega2 = bodega2;
		this.tipoT = tipoT;
		this.vendedor = vendedor;
		this.bodeguero = bodeguero;
		this.requisicion = requisicion;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
		this.timestampColumn = timestampColumn;
		this.codArt = codArt;
		this.descripcion = descripcion;
		this.cantidad = cantidad;
		this.producida = producida;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public Character getTransa() {
		return this.transa;
	}

	public void setTransa(Character transa) {
		this.transa = transa;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getBodega() {
		return this.bodega;
	}

	public void setBodega(String bodega) {
		this.bodega = bodega;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getDescri() {
		return this.descri;
	}

	public void setDescri(String descri) {
		this.descri = descri;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	public String getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(String proveedor) {
		this.proveedor = proveedor;
	}

	public String getFactura() {
		return this.factura;
	}

	public void setFactura(String factura) {
		this.factura = factura;
	}

	public String getPolisa() {
		return this.polisa;
	}

	public void setPolisa(String polisa) {
		this.polisa = polisa;
	}

	public String getCampo() {
		return this.campo;
	}

	public void setCampo(String campo) {
		this.campo = campo;
	}

	public String getBodega2() {
		return this.bodega2;
	}

	public void setBodega2(String bodega2) {
		this.bodega2 = bodega2;
	}

	public String getTipoT() {
		return this.tipoT;
	}

	public void setTipoT(String tipoT) {
		this.tipoT = tipoT;
	}

	public String getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(String vendedor) {
		this.vendedor = vendedor;
	}

	public String getBodeguero() {
		return this.bodeguero;
	}

	public void setBodeguero(String bodeguero) {
		this.bodeguero = bodeguero;
	}

	public String getRequisicion() {
		return this.requisicion;
	}

	public void setRequisicion(String requisicion) {
		this.requisicion = requisicion;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public Character getTimestampColumn() {
		return this.timestampColumn;
	}

	public void setTimestampColumn(Character timestampColumn) {
		this.timestampColumn = timestampColumn;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Float getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Float cantidad) {
		this.cantidad = cantidad;
	}

	public Float getProducida() {
		return this.producida;
	}

	public void setProducida(Float producida) {
		this.producida = producida;
	}

}
