package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cambioprecios generated by hbm2java
 */
@Entity
@Table(name = "cambioprecios")
public class CambioPrecios implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "nombre")
	private String nombre;
	
	@Column(name = "fecha_registro")
	private Date fechaRegistro;
	
	@Column(name = "precio_nuevo")
	private Float precioNuevo;
	
	@Column(name = "precio_ant")
	private Float precioAnt;
	
	@Column(name = "precio_03")
	private Float precio03;
	
	@Column(name = "precio_04")
	private Float precio04;
	
	@Column(name = "precio_05")
	private Float precio05;
	
	@Column(name = "preciooferta_nuebo")
	private Float precioOfertaNuevo;
	
	@Column(name = "preciooferta")
	private Float precioOferta;
	
	@Column(name = "fechainicio")
	private Date fechaInicio;
	
	@Column(name = "fechafinal")
	private Date fechaFinal;
	
	@Column(name = "desc_nuevo")
	private Float descNuevo;
	
	@Column(name = "desc_anterior")
	private Float descAnterior;
	
	@Column(name = "desc_02")
	private Float desc02;
	
	@Column(name = "desc_03")
	private Float desc03;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "stat_reg")
	private Character statReg;

	public CambioPrecios() {
	}

	public CambioPrecios(String codArt, String nombre, Date fechaRegistro, Float precioNuevo, Float precioAnt,
			Float precio03, Float precio04, Float precio05, Float precioOfertaNuevo, Float precioOferta,
			Date fechaInicio, Date fechaFinal, Float descNuevo, Float descAnterior, Float desc02, Float desc03,
			String usuario, Character statReg) {
		this.codArt = codArt;
		this.nombre = nombre;
		this.fechaRegistro = fechaRegistro;
		this.precioNuevo = precioNuevo;
		this.precioAnt = precioAnt;
		this.precio03 = precio03;
		this.precio04 = precio04;
		this.precio05 = precio05;
		this.precioOfertaNuevo = precioOfertaNuevo;
		this.precioOferta = precioOferta;
		this.fechaInicio = fechaInicio;
		this.fechaFinal = fechaFinal;
		this.descNuevo = descNuevo;
		this.descAnterior = descAnterior;
		this.desc02 = desc02;
		this.desc03 = desc03;
		this.usuario = usuario;
		this.statReg = statReg;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Float getPrecioNuevo() {
		return this.precioNuevo;
	}

	public void setPrecioNuevo(Float precioNuevo) {
		this.precioNuevo = precioNuevo;
	}

	public Float getPrecioAnt() {
		return this.precioAnt;
	}

	public void setPrecioAnt(Float precioAnt) {
		this.precioAnt = precioAnt;
	}

	public Float getPrecio03() {
		return this.precio03;
	}

	public void setPrecio03(Float precio03) {
		this.precio03 = precio03;
	}

	public Float getPrecio04() {
		return this.precio04;
	}

	public void setPrecio04(Float precio04) {
		this.precio04 = precio04;
	}

	public Float getPrecio05() {
		return this.precio05;
	}

	public void setPrecio05(Float precio05) {
		this.precio05 = precio05;
	}

	public Float getPrecioOfertaNuevo() {
		return this.precioOfertaNuevo;
	}

	public void setPrecioOfertaNuevo(Float precioOfertaNuevo) {
		this.precioOfertaNuevo = precioOfertaNuevo;
	}

	public Float getPrecioOferta() {
		return this.precioOferta;
	}

	public void setPrecioOferta(Float precioOferta) {
		this.precioOferta = precioOferta;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	public Float getDescNuevo() {
		return this.descNuevo;
	}

	public void setDescNuevo(Float descNuevo) {
		this.descNuevo = descNuevo;
	}

	public Float getDescAnterior() {
		return this.descAnterior;
	}

	public void setDescAnterior(Float descAnterior) {
		this.descAnterior = descAnterior;
	}

	public Float getDesc02() {
		return this.desc02;
	}

	public void setDesc02(Float desc02) {
		this.desc02 = desc02;
	}

	public Float getDesc03() {
		return this.desc03;
	}

	public void setDesc03(Float desc03) {
		this.desc03 = desc03;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

}
