package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ComprasD generated by hbm2java
 */
@Entity
@Table(name = "compras_d")
public class ComprasD implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "tipo")
	private String tipo;
	
	@Column(name = "bodega")
	private String bodega;
	
	@Column(name = "numero")
	private String numero;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "nombre")
	private String nombre;
	
	@Column(name = "nopieza")
	private String noPieza;
	
	@Column(name = "anio")
	private String anio;
	
	@Column(name = "cantidad")
	private Float cantidad;
	
	@Column(name = "costo_u")
	private Float costoU;
	
	@Column(name = "costo_total")
	private Float costoTotal;
	
	@Column(name = "impuesto")
	private Float impuesto;
	
	@Column(name = "factor")
	private Float factor;
	
	@Column(name = "precio")
	private Float precio;
	
	@Column(name = "year")
	private String year;
	
	@Column(name = "mes")
	private String mes;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;
	
	@Column(name = "vin")
	private String vin;
	
	@Column(name = "observaciones")
	private String observaciones;
	
	@Column(name = "estanteria")
	private String estanteria;
	
	@Column(name = "ubicacion")
	private String ubicacion;
	
	@Column(name = "fila")
	private String fila;

	public ComprasD() {
	}

	public ComprasD(String tipo, String bodega, String numero, Date fecha, String codArt, String year, String mes) {
		this.tipo = tipo;
		this.bodega = bodega;
		this.numero = numero;
		this.fecha = fecha;
		this.codArt = codArt;
		this.year = year;
		this.mes = mes;
	}

	public ComprasD(String tipo, String bodega, String numero, Date fecha, String codArt, String nombre, String noPieza,
			String anio, Float cantidad, Float costoU, Float costoTotal, Float impuesto, Float factor, Float precio,
			String year, String mes, Character statReg, String usuario, Date fechaIngreso, String vin,
			String observaciones, String estanteria, String ubicacion, String fila) {
		this.tipo = tipo;
		this.bodega = bodega;
		this.numero = numero;
		this.fecha = fecha;
		this.codArt = codArt;
		this.nombre = nombre;
		this.noPieza = noPieza;
		this.anio = anio;
		this.cantidad = cantidad;
		this.costoU = costoU;
		this.costoTotal = costoTotal;
		this.impuesto = impuesto;
		this.factor = factor;
		this.precio = precio;
		this.year = year;
		this.mes = mes;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
		this.vin = vin;
		this.observaciones = observaciones;
		this.estanteria = estanteria;
		this.ubicacion = ubicacion;
		this.fila = fila;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getBodega() {
		return this.bodega;
	}

	public void setBodega(String bodega) {
		this.bodega = bodega;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getNoPieza() {
		return this.noPieza;
	}

	public void setNoPieza(String noPieza) {
		this.noPieza = noPieza;
	}

	public String getAnio() {
		return this.anio;
	}

	public void setAnio(String anio) {
		this.anio = anio;
	}

	public Float getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Float cantidad) {
		this.cantidad = cantidad;
	}

	public Float getCostoU() {
		return this.costoU;
	}

	public void setCostoU(Float costoU) {
		this.costoU = costoU;
	}

	public Float getCostoTotal() {
		return this.costoTotal;
	}

	public void setCostoTotal(Float costoTotal) {
		this.costoTotal = costoTotal;
	}

	public Float getImpuesto() {
		return this.impuesto;
	}

	public void setImpuesto(Float impuesto) {
		this.impuesto = impuesto;
	}

	public Float getFactor() {
		return this.factor;
	}

	public void setFactor(Float factor) {
		this.factor = factor;
	}

	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

	public String getMes() {
		return this.mes;
	}

	public void setMes(String mes) {
		this.mes = mes;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getVin() {
		return this.vin;
	}

	public void setVin(String vin) {
		this.vin = vin;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getEstanteria() {
		return this.estanteria;
	}

	public void setEstanteria(String estanteria) {
		this.estanteria = estanteria;
	}

	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public String getFila() {
		return this.fila;
	}

	public void setFila(String fila) {
		this.fila = fila;
	}

}
