package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ComprasH generated by hbm2java
 */
@Entity
@Table(name = "compras_h")
public class ComprasH implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "tipo")
	private String tipo;
	
	@Column(name = "bodega")
	private String bodega;
	
	@Column(name = "numero")
	private String numero;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "concepto")
	private String concepto;
	
	@Column(name = "proveedor")
	private String proveedor;
	
	@Column(name = "factura")
	private String factura;
	
	@Column(name = "fecfactura")
	private Date fecFactura;
	
	@Column(name = "poliza")
	private String poliza;
	
	@Column(name = "valorfactura")
	private Float valorFactura;
	
	@Column(name = "cif")
	private Float cif;
	
	@Column(name = "fob")
	private Float fob;
	
	@Column(name = "fletemaritimo")
	private Float fleteMaritimo;
	
	@Column(name = "seguro")
	private Float seguro;
	
	@Column(name = "otrosgastosadua")
	private Float otrosGastosAdua;
	
	@Column(name = "fleteinterno")
	private Float fleteInterno;
	
	@Column(name = "tramitesaduanales")
	private Float tramitesAduanales;
	
	@Column(name = "impuestos")
	private Float impuestos;
	
	@Column(name = "almacenaje")
	private Float almacenaje;
	
	@Column(name = "otrosgastos")
	private Float otrosGastos;
	
	@Column(name = "iva")
	private Float iva;
	
	@Column(name = "tipcampoliza")
	private Float tipCamPoliza;
	
	@Column(name = "tipcamcomp")
	private Float tipCamComp;
	
	@Column(name = "factorcosto1")
	private Float factorCosto1;
	
	@Column(name = "factorcosto2")
	private Float factorCosto2;
	
	@Column(name = "factorcosto3")
	private Float factorCosto3;
	
	@Column(name = "lugarcompra")
	private String lugarCompra;
	
	@Column(name = "formacompra")
	private String formaCompra;
	
	@Column(name = "diascredito")
	private Float diasCredito;
	
	@Column(name = "cargos")
	private Float cargos;
	
	@Column(name = "abonos")
	private Float abonos;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;
	
	@Column(name = "nit")
	private String nit;

	public ComprasH() {
	}

	public ComprasH(String tipo, String bodega, String numero, Date fecha) {
		this.tipo = tipo;
		this.bodega = bodega;
		this.numero = numero;
		this.fecha = fecha;
	}

	public ComprasH(String tipo, String bodega, String numero, Date fecha, String concepto, String proveedor,
			String factura, Date fecFactura, String poliza, Float valorFactura, Float cif, Float fob,
			Float fleteMaritimo, Float seguro, Float otrosGastosAdua, Float fleteInterno, Float tramitesAduanales,
			Float impuestos, Float almacenaje, Float otrosGastos, Float iva, Float tipCamPoliza, Float tipCamComp,
			Float factorCosto1, Float factorCosto2, Float factorCosto3, String lugarCompra, String formaCompra,
			Float diasCredito, Float cargos, Float abonos, Character statReg, String usuario, Date fechaIngreso,
			String nit) {
		this.tipo = tipo;
		this.bodega = bodega;
		this.numero = numero;
		this.fecha = fecha;
		this.concepto = concepto;
		this.proveedor = proveedor;
		this.factura = factura;
		this.fecFactura = fecFactura;
		this.poliza = poliza;
		this.valorFactura = valorFactura;
		this.cif = cif;
		this.fob = fob;
		this.fleteMaritimo = fleteMaritimo;
		this.seguro = seguro;
		this.otrosGastosAdua = otrosGastosAdua;
		this.fleteInterno = fleteInterno;
		this.tramitesAduanales = tramitesAduanales;
		this.impuestos = impuestos;
		this.almacenaje = almacenaje;
		this.otrosGastos = otrosGastos;
		this.iva = iva;
		this.tipCamPoliza = tipCamPoliza;
		this.tipCamComp = tipCamComp;
		this.factorCosto1 = factorCosto1;
		this.factorCosto2 = factorCosto2;
		this.factorCosto3 = factorCosto3;
		this.lugarCompra = lugarCompra;
		this.formaCompra = formaCompra;
		this.diasCredito = diasCredito;
		this.cargos = cargos;
		this.abonos = abonos;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
		this.nit = nit;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getBodega() {
		return this.bodega;
	}

	public void setBodega(String bodega) {
		this.bodega = bodega;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

	public String getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(String proveedor) {
		this.proveedor = proveedor;
	}

	public String getFactura() {
		return this.factura;
	}

	public void setFactura(String factura) {
		this.factura = factura;
	}

	public Date getFecFactura() {
		return this.fecFactura;
	}

	public void setFecFactura(Date fecFactura) {
		this.fecFactura = fecFactura;
	}

	public String getPoliza() {
		return this.poliza;
	}

	public void setPoliza(String poliza) {
		this.poliza = poliza;
	}

	public Float getValorFactura() {
		return this.valorFactura;
	}

	public void setValorFactura(Float valorFactura) {
		this.valorFactura = valorFactura;
	}

	public Float getCif() {
		return this.cif;
	}

	public void setCif(Float cif) {
		this.cif = cif;
	}

	public Float getFob() {
		return this.fob;
	}

	public void setFob(Float fob) {
		this.fob = fob;
	}

	public Float getFleteMaritimo() {
		return this.fleteMaritimo;
	}

	public void setFleteMaritimo(Float fleteMaritimo) {
		this.fleteMaritimo = fleteMaritimo;
	}

	public Float getSeguro() {
		return this.seguro;
	}

	public void setSeguro(Float seguro) {
		this.seguro = seguro;
	}

	public Float getOtrosGastosAdua() {
		return this.otrosGastosAdua;
	}

	public void setOtrosGastosAdua(Float otrosGastosAdua) {
		this.otrosGastosAdua = otrosGastosAdua;
	}

	public Float getFleteInterno() {
		return this.fleteInterno;
	}

	public void setFleteInterno(Float fleteInterno) {
		this.fleteInterno = fleteInterno;
	}

	public Float getTramitesAduanales() {
		return this.tramitesAduanales;
	}

	public void setTramitesAduanales(Float tramitesAduanales) {
		this.tramitesAduanales = tramitesAduanales;
	}

	public Float getImpuestos() {
		return this.impuestos;
	}

	public void setImpuestos(Float impuestos) {
		this.impuestos = impuestos;
	}

	public Float getAlmacenaje() {
		return this.almacenaje;
	}

	public void setAlmacenaje(Float almacenaje) {
		this.almacenaje = almacenaje;
	}

	public Float getOtrosGastos() {
		return this.otrosGastos;
	}

	public void setOtrosGastos(Float otrosGastos) {
		this.otrosGastos = otrosGastos;
	}

	public Float getIva() {
		return this.iva;
	}

	public void setIva(Float iva) {
		this.iva = iva;
	}

	public Float getTipCamPoliza() {
		return this.tipCamPoliza;
	}

	public void setTipCamPoliza(Float tipCamPoliza) {
		this.tipCamPoliza = tipCamPoliza;
	}

	public Float getTipCamComp() {
		return this.tipCamComp;
	}

	public void setTipCamComp(Float tipCamComp) {
		this.tipCamComp = tipCamComp;
	}

	public Float getFactorCosto1() {
		return this.factorCosto1;
	}

	public void setFactorCosto1(Float factorCosto1) {
		this.factorCosto1 = factorCosto1;
	}

	public Float getFactorCosto2() {
		return this.factorCosto2;
	}

	public void setFactorCosto2(Float factorCosto2) {
		this.factorCosto2 = factorCosto2;
	}

	public Float getFactorCosto3() {
		return this.factorCosto3;
	}

	public void setFactorCosto3(Float factorCosto3) {
		this.factorCosto3 = factorCosto3;
	}

	public String getLugarCompra() {
		return this.lugarCompra;
	}

	public void setLugarCompra(String lugarCompra) {
		this.lugarCompra = lugarCompra;
	}

	public String getFormaCompra() {
		return this.formaCompra;
	}

	public void setFormaCompra(String formaCompra) {
		this.formaCompra = formaCompra;
	}

	public Float getDiasCredito() {
		return this.diasCredito;
	}

	public void setDiasCredito(Float diasCredito) {
		this.diasCredito = diasCredito;
	}

	public Float getCargos() {
		return this.cargos;
	}

	public void setCargos(Float cargos) {
		this.cargos = cargos;
	}

	public Float getAbonos() {
		return this.abonos;
	}

	public void setAbonos(Float abonos) {
		this.abonos = abonos;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

}
