package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Consultas generated by hbm2java
 */
@Entity
@Table(name = "consultas")
public class Consultas implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "marca")
	private String marca;
	
	@Column(name = "linea")
	private String linea;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "descripcion")
	private String descripcion;
	
	@Column(name = "modelo")
	private String modelo;
	
	@Column(name = "no_pieza")
	private String noPieza;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;
	
	@Column(name = "observacion")
	private String observacion;
	
	@Column(name = "usuario")
	private String usuario;

	public Consultas() {
	}

	public Consultas(String marca, String linea, String codArt, String descripcion, String modelo, String noPieza,
			Date fechaIngreso, String observacion, String usuario) {
		this.marca = marca;
		this.linea = linea;
		this.codArt = codArt;
		this.descripcion = descripcion;
		this.modelo = modelo;
		this.noPieza = noPieza;
		this.fechaIngreso = fechaIngreso;
		this.observacion = observacion;
		this.usuario = usuario;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getLinea() {
		return this.linea;
	}

	public void setLinea(String linea) {
		this.linea = linea;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getNoPieza() {
		return this.noPieza;
	}

	public void setNoPieza(String noPieza) {
		this.noPieza = noPieza;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

}
