package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Detallefac generated by hbm2java
 */
@Entity
@Table(name = "detallefac")
public class DetalleFac implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "num_dcto")
	private String numDcto;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "descripcion")
	private String descripcion;
	
	@Column(name = "debe")
	private Float debe;
	
	@Column(name = "pu")
	private Float pu;
	
	@Column(name = "dq")
	private Float dq;
	
	@Column(name = "registro")
	private String registro;
	
	@Column(name = "tipo")
	private String tipo;
	
	@Column(name = "dcto_lin")
	private Float dctoLin;
	
	@Column(name = "item")
	private Long item;
	
	@Column(name = "dctofac")
	private Float dctoFac;
	
	@Column(name = "neto")
	private Float neto;
	
	@Column(name = "ajuste")
	private Float ajuste;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "cq")
	private Float cq;

	public DetalleFac() {
	}

	public DetalleFac(String numDcto, String codArt, String registro) {
		this.numDcto = numDcto;
		this.codArt = codArt;
		this.registro = registro;
	}

	public DetalleFac(String numDcto, String codArt, String descripcion, Float debe, Float pu, Float dq,
			String registro, String tipo, Float dctoLin, Long item, Float dctoFac, Float neto, Float ajuste, Date fecha,
			Float cq) {
		this.numDcto = numDcto;
		this.codArt = codArt;
		this.descripcion = descripcion;
		this.debe = debe;
		this.pu = pu;
		this.dq = dq;
		this.registro = registro;
		this.tipo = tipo;
		this.dctoLin = dctoLin;
		this.item = item;
		this.dctoFac = dctoFac;
		this.neto = neto;
		this.ajuste = ajuste;
		this.fecha = fecha;
		this.cq = cq;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getNumDcto() {
		return this.numDcto;
	}

	public void setNumDcto(String numDcto) {
		this.numDcto = numDcto;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Float getDebe() {
		return this.debe;
	}

	public void setDebe(Float debe) {
		this.debe = debe;
	}

	public Float getPu() {
		return this.pu;
	}

	public void setPu(Float pu) {
		this.pu = pu;
	}

	public Float getDq() {
		return this.dq;
	}

	public void setDq(Float dq) {
		this.dq = dq;
	}

	public String getRegistro() {
		return this.registro;
	}

	public void setRegistro(String registro) {
		this.registro = registro;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Float getDctoLin() {
		return this.dctoLin;
	}

	public void setDctoLin(Float dctoLin) {
		this.dctoLin = dctoLin;
	}

	public Long getItem() {
		return this.item;
	}

	public void setItem(Long item) {
		this.item = item;
	}

	public Float getDctoFac() {
		return this.dctoFac;
	}

	public void setDctoFac(Float dctoFac) {
		this.dctoFac = dctoFac;
	}

	public Float getNeto() {
		return this.neto;
	}

	public void setNeto(Float neto) {
		this.neto = neto;
	}

	public Float getAjuste() {
		return this.ajuste;
	}

	public void setAjuste(Float ajuste) {
		this.ajuste = ajuste;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Float getCq() {
		return this.cq;
	}

	public void setCq(Float cq) {
		this.cq = cq;
	}

}
