package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Grupos. generated by hbm2java
 */
@Entity
@Table(name = "grupos$")
public class GruposS implements java.io.Serializable {

	@Id
	@Column(name = "id_grupos$")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idGruposS;
	
	@Column(name = "codigo")
	private String codigo;
	
	@Column(name = "nombre_grupo")
	private String nombreGrupo;
	
	@Column(name = "varios")
	private String varios;

	public GruposS() {
	}

	public GruposS(String codigo, String nombreGrupo, String varios) {
		this.codigo = codigo;
		this.nombreGrupo = nombreGrupo;
		this.varios = varios;
	}

	public Long getIdGruposS() {
		return this.idGruposS;
	}

	public void setIdGruposS(Long idGruposS) {
		this.idGruposS = idGruposS;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombreGrupo() {
		return this.nombreGrupo;
	}

	public void setNombreGrupo(String nombreGrupo) {
		this.nombreGrupo = nombreGrupo;
	}

	public String getVarios() {
		return this.varios;
	}

	public void setVarios(String varios) {
		this.varios = varios;
	}

}
