package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Grupos generated by hbm2java
 */
@Entity
@Table(name = "grupos")
public class Grupos implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "grupos")
	private String grupos;
	
	@Column(name = "descrip_grp")
	private String descripGrp;
	
	@Column(name = "orden")
	private String orden;
	
	@Column(name = "encabeza")
	private String encabeza;
	
	@Column(name = "encabeza1")
	private String encabeza1;
	
	@Column(name = "encabeza2")
	private String encabeza2;
	
	@Column(name = "encabeza3")
	private String encabeza3;
	
	@Column(name = "encabeza4")
	private String encabeza4;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public Grupos() {
	}

	public Grupos(String grupos, String descripGrp, String orden, String encabeza, String encabeza1, String encabeza2,
			String encabeza3, String encabeza4, Character statReg, String usuario, Date fechaIngreso) {
		this.grupos = grupos;
		this.descripGrp = descripGrp;
		this.orden = orden;
		this.encabeza = encabeza;
		this.encabeza1 = encabeza1;
		this.encabeza2 = encabeza2;
		this.encabeza3 = encabeza3;
		this.encabeza4 = encabeza4;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getGrupos() {
		return this.grupos;
	}

	public void setGrupos(String grupos) {
		this.grupos = grupos;
	}

	public String getDescripGrp() {
		return this.descripGrp;
	}

	public void setDescripGrp(String descripGrp) {
		this.descripGrp = descripGrp;
	}

	public String getOrden() {
		return this.orden;
	}

	public void setOrden(String orden) {
		this.orden = orden;
	}

	public String getEncabeza() {
		return this.encabeza;
	}

	public void setEncabeza(String encabeza) {
		this.encabeza = encabeza;
	}

	public String getEncabeza1() {
		return this.encabeza1;
	}

	public void setEncabeza1(String encabeza1) {
		this.encabeza1 = encabeza1;
	}

	public String getEncabeza2() {
		return this.encabeza2;
	}

	public void setEncabeza2(String encabeza2) {
		this.encabeza2 = encabeza2;
	}

	public String getEncabeza3() {
		return this.encabeza3;
	}

	public void setEncabeza3(String encabeza3) {
		this.encabeza3 = encabeza3;
	}

	public String getEncabeza4() {
		return this.encabeza4;
	}

	public void setEncabeza4(String encabeza4) {
		this.encabeza4 = encabeza4;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
