package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Hoja1. generated by hbm2java
 */
@Entity
@Table(name = "hoja1$")
public class Hoja1S implements java.io.Serializable {

	@Id
	@Column(name = "id_hoja1$")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idHoja1S;
	
	@Column(name = "cia")
	private Character cia;
	
	@Column(name = "anioactual")
	private String anioActual;
	
	@Column(name = "mesactual")
	private String mesActual;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "bodega")
	private String bodega;
	
	@Column(name = "nopieza")
	private String noPieza;
	
	@Column(name = "anio")
	private String anio;
	
	@Column(name = "saldoinicial")
	private String saldoInicial;
	
	@Column(name = "entradas")
	private String entradas;
	
	@Column(name = "salidas")
	private String salidas;
	
	@Column(name = "fisico")
	private String fisico;
	
	@Column(name = "kardex")
	private String kardex;
	
	@Column(name = "fechulfis")
	private String fechUlFis;
	
	@Column(name = "mesact")
	private String mesAct;
	
	@Column(name = "pedidos")
	private String pedidos;
	
	@Column(name = "fechapedido")
	private String fechaPedido;
	
	@Column(name = "malestado")
	private String malEstado;
	
	@Column(name = "nomotor")
	private String noMotor;
	
	@Column(name = "nochasis")
	private String noChasis;
	
	@Column(name = "mecanismo")
	private String mecanismo;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private String fechaIngreso;
	
	@Column(name = "calidad")
	private String calidad;
	
	@Column(name = "vin")
	private String vin;
	
	@Column(name = "observaciones")
	private String observaciones;
	
	@Column(name = "repuestos")
	private String repuestos;
	
	@Column(name = "marca")
	private String marca;
	
	@Column(name = "linea")
	private String linea;
	
	@Column(name = "lado")
	private String lado;
	
	@Column(name = "auto")
	private Float auto;
	
	@Column(name = "codig")
	private String codig;
	
	@Column(name = "estanteria")
	private Float estanteria;
	
	@Column(name = "locacionh")
	private Float locacionH;
	
	@Column(name = "locacionv")
	private String locacionV;
	
	@Column(name = "precio")
	private Float precio;
	
	@Column(name = "f12")
	private String f12;
	
	@Column(name = "f13")
	private String f13;
	
	@Column(name = "cod_marca")
	private String codMarca;
	
	@Column(name = "cod_linea")
	private String codLinea;
	
	@Column(name = "cod_grupos")
	private String codGrupos;
	
	@Column(name = "cod_articulos")
	private String codArticulos;

	public Hoja1S() {
	}

	public Hoja1S(Character cia, String anioActual, String mesActual, String codArt, String bodega, String noPieza,
			String anio, String saldoInicial, String entradas, String salidas, String fisico, String kardex,
			String fechUlFis, String mesAct, String pedidos, String fechaPedido, String malEstado, String noMotor,
			String noChasis, String mecanismo, Character statReg, String usuario, String fechaIngreso, String calidad,
			String vin, String observaciones, String repuestos, String marca, String linea, String lado, Float auto,
			String codig, Float estanteria, Float locacionH, String locacionV, Float precio, String f12, String f13,
			String codMarca, String codLinea, String codGrupos, String codArticulos) {
		this.cia = cia;
		this.anioActual = anioActual;
		this.mesActual = mesActual;
		this.codArt = codArt;
		this.bodega = bodega;
		this.noPieza = noPieza;
		this.anio = anio;
		this.saldoInicial = saldoInicial;
		this.entradas = entradas;
		this.salidas = salidas;
		this.fisico = fisico;
		this.kardex = kardex;
		this.fechUlFis = fechUlFis;
		this.mesAct = mesAct;
		this.pedidos = pedidos;
		this.fechaPedido = fechaPedido;
		this.malEstado = malEstado;
		this.noMotor = noMotor;
		this.noChasis = noChasis;
		this.mecanismo = mecanismo;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
		this.calidad = calidad;
		this.vin = vin;
		this.observaciones = observaciones;
		this.repuestos = repuestos;
		this.marca = marca;
		this.linea = linea;
		this.lado = lado;
		this.auto = auto;
		this.codig = codig;
		this.estanteria = estanteria;
		this.locacionH = locacionH;
		this.locacionV = locacionV;
		this.precio = precio;
		this.f12 = f12;
		this.f13 = f13;
		this.codMarca = codMarca;
		this.codLinea = codLinea;
		this.codGrupos = codGrupos;
		this.codArticulos = codArticulos;
	}

	public Long getIdHoja1S() {
		return this.idHoja1S;
	}

	public void setIdHoja1S(Long idHoja1S) {
		this.idHoja1S = idHoja1S;
	}

	public Character getCia() {
		return this.cia;
	}

	public void setCia(Character cia) {
		this.cia = cia;
	}

	public String getAnioActual() {
		return this.anioActual;
	}

	public void setAnioActual(String anioActual) {
		this.anioActual = anioActual;
	}

	public String getMesActual() {
		return this.mesActual;
	}

	public void setMesActual(String mesActual) {
		this.mesActual = mesActual;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getBodega() {
		return this.bodega;
	}

	public void setBodega(String bodega) {
		this.bodega = bodega;
	}

	public String getNoPieza() {
		return this.noPieza;
	}

	public void setNoPieza(String noPieza) {
		this.noPieza = noPieza;
	}

	public String getAnio() {
		return this.anio;
	}

	public void setAnio(String anio) {
		this.anio = anio;
	}

	public String getSaldoInicial() {
		return this.saldoInicial;
	}

	public void setSaldoInicial(String saldoInicial) {
		this.saldoInicial = saldoInicial;
	}

	public String getEntradas() {
		return this.entradas;
	}

	public void setEntradas(String entradas) {
		this.entradas = entradas;
	}

	public String getSalidas() {
		return this.salidas;
	}

	public void setSalidas(String salidas) {
		this.salidas = salidas;
	}

	public String getFisico() {
		return this.fisico;
	}

	public void setFisico(String fisico) {
		this.fisico = fisico;
	}

	public String getKardex() {
		return this.kardex;
	}

	public void setKardex(String kardex) {
		this.kardex = kardex;
	}

	public String getFechUlFis() {
		return this.fechUlFis;
	}

	public void setFechUlFis(String fechUlFis) {
		this.fechUlFis = fechUlFis;
	}

	public String getMesAct() {
		return this.mesAct;
	}

	public void setMesAct(String mesAct) {
		this.mesAct = mesAct;
	}

	public String getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(String pedidos) {
		this.pedidos = pedidos;
	}

	public String getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(String fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	public String getMalEstado() {
		return this.malEstado;
	}

	public void setMalEstado(String malEstado) {
		this.malEstado = malEstado;
	}

	public String getNoMotor() {
		return this.noMotor;
	}

	public void setNoMotor(String noMotor) {
		this.noMotor = noMotor;
	}

	public String getNoChasis() {
		return this.noChasis;
	}

	public void setNoChasis(String noChasis) {
		this.noChasis = noChasis;
	}

	public String getMecanismo() {
		return this.mecanismo;
	}

	public void setMecanismo(String mecanismo) {
		this.mecanismo = mecanismo;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(String fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getCalidad() {
		return this.calidad;
	}

	public void setCalidad(String calidad) {
		this.calidad = calidad;
	}

	public String getVin() {
		return this.vin;
	}

	public void setVin(String vin) {
		this.vin = vin;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public String getRepuestos() {
		return this.repuestos;
	}

	public void setRepuestos(String repuestos) {
		this.repuestos = repuestos;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getLinea() {
		return this.linea;
	}

	public void setLinea(String linea) {
		this.linea = linea;
	}

	public String getLado() {
		return this.lado;
	}

	public void setLado(String lado) {
		this.lado = lado;
	}

	public Float getAuto() {
		return this.auto;
	}

	public void setAuto(Float auto) {
		this.auto = auto;
	}

	public String getCodig() {
		return this.codig;
	}

	public void setCodig(String codig) {
		this.codig = codig;
	}

	public Float getEstanteria() {
		return this.estanteria;
	}

	public void setEstanteria(Float estanteria) {
		this.estanteria = estanteria;
	}

	public Float getLocacionH() {
		return this.locacionH;
	}

	public void setLocacionH(Float locacionH) {
		this.locacionH = locacionH;
	}

	public String getLocacionV() {
		return this.locacionV;
	}

	public void setLocacionV(String locacionV) {
		this.locacionV = locacionV;
	}

	public Float getPrecio() {
		return this.precio;
	}

	public void setPrecio(Float precio) {
		this.precio = precio;
	}

	public String getF12() {
		return this.f12;
	}

	public void setF12(String f12) {
		this.f12 = f12;
	}

	public String getF13() {
		return this.f13;
	}

	public void setF13(String f13) {
		this.f13 = f13;
	}

	public String getCodMarca() {
		return this.codMarca;
	}

	public void setCodMarca(String codMarca) {
		this.codMarca = codMarca;
	}

	public String getCodLinea() {
		return this.codLinea;
	}

	public void setCodLinea(String codLinea) {
		this.codLinea = codLinea;
	}

	public String getCodGrupos() {
		return this.codGrupos;
	}

	public void setCodGrupos(String codGrupos) {
		this.codGrupos = codGrupos;
	}

	public String getCodArticulos() {
		return this.codArticulos;
	}

	public void setCodArticulos(String codArticulos) {
		this.codArticulos = codArticulos;
	}

}
