package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Ingreso generated by hbm2java
 */
@Entity
@Table(name = "ingreso")
public class Ingreso implements java.io.Serializable {

	@Id
	@Column(name = "id_ingreso")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idIngreso;

	@Column(name = "id_usuario")
	private Short idUsuario;

	@Column(name = "no_ingreso")
	private Short noIngreso;

	@Column(name = "id_grupo")
	private Short idGrupo;

	@Column(name = "no_pieza")
	private String noPieza;

	@Column(name = "id_repuesto")
	private String idRepuesto;

	@Column(name = "id_linea")
	private String idLinea;

	@Column(name = "fecha")
	private Date fecha;

	@Column(name = "estado")
	private String estado;

	@Column(name = "generales")
	private String generales;

	@Column(name = "anio")
	private String anio;

	@Column(name = "no_bodega")
	private String noBodega;

	@Column(name = "ubicacion")
	private String ubicacion;
	
	@Column(name = "fila")
	private String fila;
	
	@Column(name = "estanteria")
	private String estanteria;
	
	@Column(name = "precio")
	private Long precio;
	
	@Column(name = "precio_venta")
	private Long precioVenta;
	
	@Column(name = "cod_marca")
	private String codMarca;
	
	@Column(name = "cod_linea")
	private String codLinea;
	
	@Column(name = "cod_grupo")
	private String codGrupo;
	
	@Column(name = "descripcion")
	private String descripcion;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "stat_reg")
	private String statReg;

	public Ingreso() {
	}

	public Ingreso(Short idUsuario, Short noIngreso, Short idGrupo, String noPieza, String idRepuesto, String idLinea,
			Date fecha, String estado, String generales, String anio, String noBodega, String ubicacion, String fila,
			String estanteria, Long precio, Long precioVenta, String codMarca, String codLinea, String codGrupo,
			String descripcion, String codArt, String statReg) {
		this.idUsuario = idUsuario;
		this.noIngreso = noIngreso;
		this.idGrupo = idGrupo;
		this.noPieza = noPieza;
		this.idRepuesto = idRepuesto;
		this.idLinea = idLinea;
		this.fecha = fecha;
		this.estado = estado;
		this.generales = generales;
		this.anio = anio;
		this.noBodega = noBodega;
		this.ubicacion = ubicacion;
		this.fila = fila;
		this.estanteria = estanteria;
		this.precio = precio;
		this.precioVenta = precioVenta;
		this.codMarca = codMarca;
		this.codLinea = codLinea;
		this.codGrupo = codGrupo;
		this.descripcion = descripcion;
		this.codArt = codArt;
		this.statReg = statReg;
	}

	public Long getIdIngreso() {
		return this.idIngreso;
	}

	public void setIdIngreso(Long idIngreso) {
		this.idIngreso = idIngreso;
	}

	public Short getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(Short idUsuario) {
		this.idUsuario = idUsuario;
	}

	public Short getNoIngreso() {
		return this.noIngreso;
	}

	public void setNoIngreso(Short noIngreso) {
		this.noIngreso = noIngreso;
	}

	public Short getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(Short idGrupo) {
		this.idGrupo = idGrupo;
	}

	public String getNoPieza() {
		return this.noPieza;
	}

	public void setNoPieza(String noPieza) {
		this.noPieza = noPieza;
	}

	public String getIdRepuesto() {
		return this.idRepuesto;
	}

	public void setIdRepuesto(String idRepuesto) {
		this.idRepuesto = idRepuesto;
	}

	public String getIdLinea() {
		return this.idLinea;
	}

	public void setIdLinea(String idLinea) {
		this.idLinea = idLinea;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getGenerales() {
		return this.generales;
	}

	public void setGenerales(String generales) {
		this.generales = generales;
	}

	public String getAnio() {
		return this.anio;
	}

	public void setAnio(String anio) {
		this.anio = anio;
	}

	public String getNoBodega() {
		return this.noBodega;
	}

	public void setNoBodega(String noBodega) {
		this.noBodega = noBodega;
	}

	public String getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(String ubicacion) {
		this.ubicacion = ubicacion;
	}

	public String getFila() {
		return this.fila;
	}

	public void setFila(String fila) {
		this.fila = fila;
	}

	public String getEstanteria() {
		return this.estanteria;
	}

	public void setEstanteria(String estanteria) {
		this.estanteria = estanteria;
	}

	public Long getPrecio() {
		return this.precio;
	}

	public void setPrecio(Long precio) {
		this.precio = precio;
	}

	public Long getPrecioVenta() {
		return this.precioVenta;
	}

	public void setPrecioVenta(Long precioVenta) {
		this.precioVenta = precioVenta;
	}

	public String getCodMarca() {
		return this.codMarca;
	}

	public void setCodMarca(String codMarca) {
		this.codMarca = codMarca;
	}

	public String getCodLinea() {
		return this.codLinea;
	}

	public void setCodLinea(String codLinea) {
		this.codLinea = codLinea;
	}

	public String getCodGrupo() {
		return this.codGrupo;
	}

	public void setCodGrupo(String codGrupo) {
		this.codGrupo = codGrupo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getStatReg() {
		return this.statReg;
	}

	public void setStatReg(String statReg) {
		this.statReg = statReg;
	}

}
