package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Inventario. generated by hbm2java
 */
@Entity
@Table(name = "inventario$")
public class InventarioS implements java.io.Serializable {

	@Id
	@Column(name = "id_inventario$")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idInventarioS;
	
	@Column(name = "repuestos")
	private String repuestos;
	
	@Column(name = "marca")
	private String marca;
	
	@Column(name = "linea")
	private String linea;
	
	@Column(name = "anio")
	private String anio;
	
	@Column(name = "lado")
	private String lado;
	
	@Column(name = "auto")
	private String auto;
	
	@Column(name = "f7")
	private String f7;
	
	@Column(name = "estan")
	private Long estan;
	
	@Column(name = "precio")
	private Long precio;
	
	@Column(name = "n_envio")
	private String nEnvio;
	
	@Column(name = "fecha")
	private Date fecha;
	
	@Column(name = "p_venta")
	private Long pVenta;
	
	@Column(name = "cod_gruppo")
	private String codGruppo;
	
	@Column(name = "codigo_grupo")
	private String codigoGrupo;
	
	@Column(name = "cod_marca")
	private String codMarca;
	
	@Column(name = "cod_linea")
	private String codLinea;
	
	@Column(name = "modelo")
	private String modelo;
	
	@Column(name = "cod_articulo")
	private String codArticulo;
	
	@Column(name = "cod_art")
	private String codArt;

	public InventarioS() {
	}

	public InventarioS(String repuestos, String marca, String linea, String anio, String lado, String auto, String f7,
			Long estan, Long precio, String nEnvio, Date fecha, Long pVenta, String codGruppo, String codigoGrupo,
			String codMarca, String codLinea, String modelo, String codArticulo, String codArt) {
		this.repuestos = repuestos;
		this.marca = marca;
		this.linea = linea;
		this.anio = anio;
		this.lado = lado;
		this.auto = auto;
		this.f7 = f7;
		this.estan = estan;
		this.precio = precio;
		this.nEnvio = nEnvio;
		this.fecha = fecha;
		this.pVenta = pVenta;
		this.codGruppo = codGruppo;
		this.codigoGrupo = codigoGrupo;
		this.codMarca = codMarca;
		this.codLinea = codLinea;
		this.modelo = modelo;
		this.codArticulo = codArticulo;
		this.codArt = codArt;
	}

	public Long getIdInventarioS() {
		return this.idInventarioS;
	}

	public void setIdInventarioS(Long idInventarioS) {
		this.idInventarioS = idInventarioS;
	}

	public String getRepuestos() {
		return this.repuestos;
	}

	public void setRepuestos(String repuestos) {
		this.repuestos = repuestos;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getLinea() {
		return this.linea;
	}

	public void setLinea(String linea) {
		this.linea = linea;
	}

	public String getAnio() {
		return this.anio;
	}

	public void setAnio(String anio) {
		this.anio = anio;
	}

	public String getLado() {
		return this.lado;
	}

	public void setLado(String lado) {
		this.lado = lado;
	}

	public String getAuto() {
		return this.auto;
	}

	public void setAuto(String auto) {
		this.auto = auto;
	}

	public String getF7() {
		return this.f7;
	}

	public void setF7(String f7) {
		this.f7 = f7;
	}

	public Long getEstan() {
		return this.estan;
	}

	public void setEstan(Long estan) {
		this.estan = estan;
	}

	public Long getPrecio() {
		return this.precio;
	}

	public void setPrecio(Long precio) {
		this.precio = precio;
	}

	public String getNEnvio() {
		return this.nEnvio;
	}

	public void setNEnvio(String nEnvio) {
		this.nEnvio = nEnvio;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Long getPVenta() {
		return this.pVenta;
	}

	public void setPVenta(Long pVenta) {
		this.pVenta = pVenta;
	}

	public String getCodGruppo() {
		return this.codGruppo;
	}

	public void setCodGruppo(String codGruppo) {
		this.codGruppo = codGruppo;
	}

	public String getCodigoGrupo() {
		return this.codigoGrupo;
	}

	public void setCodigoGrupo(String codigoGrupo) {
		this.codigoGrupo = codigoGrupo;
	}

	public String getCodMarca() {
		return this.codMarca;
	}

	public void setCodMarca(String codMarca) {
		this.codMarca = codMarca;
	}

	public String getCodLinea() {
		return this.codLinea;
	}

	public void setCodLinea(String codLinea) {
		this.codLinea = codLinea;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getCodArticulo() {
		return this.codArticulo;
	}

	public void setCodArticulo(String codArticulo) {
		this.codArticulo = codArticulo;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

}
