package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MaebodDetPadre generated by hbm2java
 */
@Entity
@Table(name = "maebod_det_padre")
public class MaebodDetPadre implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "cod_art_padre")
	private String codArtPadre;
	
	@Column(name = "bodega_padre")
	private String bodegaPadre;
	
	@Column(name = "nopieza_padre")
	private String noPiezaPadre;
	
	@Column(name = "anio_padre")
	private String anioPadre;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "bodega")
	private String bodega;
	
	@Column(name = "nopieza")
	private String noPieza;
	
	@Column(name = "anio")
	private String anio;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public MaebodDetPadre() {
	}

	public MaebodDetPadre(String codArtPadre, String bodegaPadre, String noPiezaPadre, String anioPadre, String codArt,
			String bodega, String noPieza, String anio, Character statReg, String usuario, Date fechaIngreso) {
		this.codArtPadre = codArtPadre;
		this.bodegaPadre = bodegaPadre;
		this.noPiezaPadre = noPiezaPadre;
		this.anioPadre = anioPadre;
		this.codArt = codArt;
		this.bodega = bodega;
		this.noPieza = noPieza;
		this.anio = anio;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getCodArtPadre() {
		return this.codArtPadre;
	}

	public void setCodArtPadre(String codArtPadre) {
		this.codArtPadre = codArtPadre;
	}

	public String getBodegaPadre() {
		return this.bodegaPadre;
	}

	public void setBodegaPadre(String bodegaPadre) {
		this.bodegaPadre = bodegaPadre;
	}

	public String getNoPiezaPadre() {
		return this.noPiezaPadre;
	}

	public void setNoPiezaPadre(String noPiezaPadre) {
		this.noPiezaPadre = noPiezaPadre;
	}

	public String getAnioPadre() {
		return this.anioPadre;
	}

	public void setAnioPadre(String anioPadre) {
		this.anioPadre = anioPadre;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getBodega() {
		return this.bodega;
	}

	public void setBodega(String bodega) {
		this.bodega = bodega;
	}

	public String getNoPieza() {
		return this.noPieza;
	}

	public void setNoPieza(String noPieza) {
		this.noPieza = noPieza;
	}

	public String getAnio() {
		return this.anio;
	}

	public void setAnio(String anio) {
		this.anio = anio;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
