package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MaebodDet generated by hbm2java
 */
@Entity
@Table(name = "maebod_det")
public class MaebodDet implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "anioactual")
	private String anioactual;
	
	@Column(name = "mesactual")
	private String mesactual;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "bodega")
	private String bodega;
	
	@Column(name = "nopieza")
	private String noPieza;
	
	@Column(name = "anio")
	private String anio;
	
	@Column(name = "saldoinicial")
	private Float saldoInicial;
	
	@Column(name = "entradas")
	private Float entradas;
	
	@Column(name = "salidas")
	private Float salidas;
	
	@Column(name = "fisico")
	private Float fisico;
	
	@Column(name = "kardex")
	private Float kardex;
	
	@Column(name = "fechulfis")
	private Date fechUlFis;
	
	@Column(name = "mesact")
	private String mesAct;
	
	@Column(name = "pedidos")
	private Float pedidos;
	
	@Column(name = "fechapedido")
	private Date fechaPedido;
	
	@Column(name = "malestado")
	private Float malEstado;
	
	@Column(name = "estanteria")
	private String estanteria;
	
	@Column(name = "locacionh")
	private String locacionH;
	
	@Column(name = "locacionv")
	private String locacionV;
	
	@Column(name = "nomotor")
	private String noMotor;
	
	@Column(name = "nochasis")
	private String noChasis;
	
	@Column(name = "mecanismo")
	private String mecanismo;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;
	
	@Column(name = "calidad")
	private String calidad;
	
	@Column(name = "vin")
	private String vin;
	
	@Column(name = "observaciones")
	private String observaciones;

	public MaebodDet() {
	}

	public MaebodDet(String anioActual, String mesActual, String codArt, String bodega, String noPieza, String anio,
			Float saldoInicial, Float entradas, Float salidas, Float fisico, Float kardex, Date fechUlFis,
			String mesAct, Float pedidos, Date fechaPedido, Float malEstado, String estanteria, String locacionH,
			String locacionV, String noMotor, String noChasis, String mecanismo, Character statReg, String usuario,
			Date fechaIngreso, String calidad, String vin, String observaciones) {
		this.anioactual = anioactual;
		this.mesactual = mesactual;
		this.codArt = codArt;
		this.bodega = bodega;
		this.noPieza = noPieza;
		this.anio = anio;
		this.saldoInicial = saldoInicial;
		this.entradas = entradas;
		this.salidas = salidas;
		this.fisico = fisico;
		this.kardex = kardex;
		this.fechUlFis = fechUlFis;
		this.mesAct = mesAct;
		this.pedidos = pedidos;
		this.fechaPedido = fechaPedido;
		this.malEstado = malEstado;
		this.estanteria = estanteria;
		this.locacionH = locacionH;
		this.locacionV = locacionV;
		this.noMotor = noMotor;
		this.noChasis = noChasis;
		this.mecanismo = mecanismo;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
		this.calidad = calidad;
		this.vin = vin;
		this.observaciones = observaciones;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getAnioactual() {
		return this.anioactual;
	}

	public void setAnioactual(String anioactual) {
		this.anioactual = anioactual;
	}

	public String getMesactual() {
		return this.mesactual;
	}

	public void setMesactual(String mesactual) {
		this.mesactual = mesactual;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getBodega() {
		return this.bodega;
	}

	public void setBodega(String bodega) {
		this.bodega = bodega;
	}

	public String getNoPieza() {
		return this.noPieza;
	}

	public void setNoPieza(String noPieza) {
		this.noPieza = noPieza;
	}

	public String getAnio() {
		return this.anio;
	}

	public void setAnio(String anio) {
		this.anio = anio;
	}

	public Float getSaldoInicial() {
		return this.saldoInicial;
	}

	public void setSaldoInicial(Float saldoInicial) {
		this.saldoInicial = saldoInicial;
	}

	public Float getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Float entradas) {
		this.entradas = entradas;
	}

	public Float getSalidas() {
		return this.salidas;
	}

	public void setSalidas(Float salidas) {
		this.salidas = salidas;
	}

	public Float getFisico() {
		return this.fisico;
	}

	public void setFisico(Float fisico) {
		this.fisico = fisico;
	}

	public Float getKardex() {
		return this.kardex;
	}

	public void setKardex(Float kardex) {
		this.kardex = kardex;
	}

	public Date getFechUlFis() {
		return this.fechUlFis;
	}

	public void setFechUlFis(Date fechUlFis) {
		this.fechUlFis = fechUlFis;
	}

	public String getMesAct() {
		return this.mesAct;
	}

	public void setMesAct(String mesAct) {
		this.mesAct = mesAct;
	}

	public Float getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Float pedidos) {
		this.pedidos = pedidos;
	}

	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	public Float getMalEstado() {
		return this.malEstado;
	}

	public void setMalEstado(Float malEstado) {
		this.malEstado = malEstado;
	}

	public String getEstanteria() {
		return this.estanteria;
	}

	public void setEstanteria(String estanteria) {
		this.estanteria = estanteria;
	}

	public String getLocacionh() {
		return this.locacionH;
	}

	public void setLocacionH(String locacionH) {
		this.locacionH = locacionH;
	}

	public String getLocacionV() {
		return this.locacionV;
	}

	public void setLocacionV(String locacionV) {
		this.locacionV = locacionV;
	}

	public String getNoMotor() {
		return this.noMotor;
	}

	public void setNoMotor(String noMotor) {
		this.noMotor = noMotor;
	}

	public String getNoChasis() {
		return this.noChasis;
	}

	public void setNoChasis(String noChasis) {
		this.noChasis = noChasis;
	}

	public String getMecanismo() {
		return this.mecanismo;
	}

	public void setMecanismo(String mecanismo) {
		this.mecanismo = mecanismo;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public String getCalidad() {
		return this.calidad;
	}

	public void setCalidad(String calidad) {
		this.calidad = calidad;
	}

	public String getVin() {
		return this.vin;
	}

	public void setVin(String vin) {
		this.vin = vin;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

}
