package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Maestro1 generated by hbm2java
 */
@Entity
@Table(name = "maestro1")
public class Maestro1 implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "cod_art")
	private String codArt;
	
	@Column(name = "nombre")
	private String nombre;
	
	@Column(name = "minimo")
	private Float minimo;
	
	@Column(name = "maximo")
	private Float maximo;
	
	@Column(name = "capacidad")
	private String capacidad;
	
	@Column(name = "marca")
	private String marca;
	
	@Column(name = "linea")
	private String linea;
	
	@Column(name = "medida")
	private String medida;
	
	@Column(name = "modulo")
	private String modulo;
	
	@Column(name = "clase")
	private String clase;
	
	@Column(name = "posicion")
	private String posicion;
	
	@Column(name = "lado")
	private String lado;
	
	@Column(name = "parte")
	private String parte;
	
	@Column(name = "precio_01")
	private Float precio01;
	
	@Column(name = "precio_02")
	private Float precio02;
	
	@Column(name = "precio_03")
	private Float precio03;
	
	@Column(name = "precio_04")
	private Float precio04;
	
	@Column(name = "precio_05")
	private Float precio05;
	
	@Column(name = "precio_06")
	private Float precio06;
	
	@Column(name = "costo_quet")
	private Float costoQuet;
	
	@Column(name = "costo_dola")
	private Float costoDola;
	
	@Column(name = "costo_dolar")
	private Float costoDolar;
	
	@Column(name = "provee")
	private String provee;
	
	@Column(name = "saldoinicial")
	private Float saldoInicial;
	
	@Column(name = "entradas")
	private Float entradas;
	
	@Column(name = "salidas")
	private Float salidas;
	
	@Column(name = "costo_q_a")
	private Float costoQA;
	
	@Column(name = "costo_d_a")
	private Float costoDA;
	
	@Column(name = "ul_costo_q")
	private Float ulCostoQ;
	
	@Column(name = "ul_costo_d")
	private Float ulCostoD;
	
	@Column(name = "tasa")
	private Float tasa;
	
	@Column(name = "ul_tasa")
	private Float ulTasa;
	
	@Column(name = "fechulcomp")
	private Date fechUlComp;
	
	@Column(name = "fechcompant")
	private Date fechCompAnt;
	
	@Column(name = "fob_ul")
	private Float fobUl;
	
	@Column(name = "fob_ant")
	private Float fobAnt;
	
	@Column(name = "flete_ul")
	private Float fleteUl;
	
	@Column(name = "flete_ant")
	private Float fleteAnt;
	
	@Column(name = "seguro_ul")
	private Float seguroUl;
	
	@Column(name = "seguro_ant")
	private Float seguroAnt;
	
	@Column(name = "otrosgastos_ul")
	private Float otrosGastosUl;
	
	@Column(name = "otrosgastos_ant")
	private Float otrosGastosAnt;
	
	@Column(name = "codigobarras")
	private Float codigoBarras;
	
	@Column(name = "codigoalterno")
	private String codigoAlterno;
	
	@Column(name = "codigoanterior")
	private String codigoAnterior;
	
	@Column(name = "diam")
	private String diam;
	
	@Column(name = "long_")
	private String long_;
	
	@Column(name = "cantidadxcaja")
	private Float cantidadXCaja;
	
	@Column(name = "cnt")
	private Float cnt;
	
	@Column(name = "pesoxpiesas")
	private Float pesoXPiesas;
	
	@Column(name = "preciooferta")
	private Float precioOferta;
	
	@Column(name = "fechainicio")
	private Date fechaInicio;
	
	@Column(name = "fechafinal")
	private Date fechaFinal;
	
	@Column(name = "cos_depre")
	private Float cosDepre;
	
	@Column(name = "costo_cif")
	private Float costoCif;
	
	@Column(name = "gastos")
	private Float gastos;
	
	@Column(name = "existe")
	private Float existe;
	
	@Column(name = "garantia")
	private String garantia;
	
	@Column(name = "grupo")
	private String grupo;
	
	@Column(name = "descripcion")
	private String descripcion;
	
	@Column(name = "desc_01")
	private Float desc01;
	
	@Column(name = "desc_02")
	private Float desc02;
	
	@Column(name = "desc_03")
	private Float desc03;
	
	@Column(name = "cod_marca")
	private String codMarca;
	
	@Column(name = "cod_linea")
	private String codLinea;
	
	@Column(name = "cod_modulo")
	private String codModulo;
	
	@Column(name = "cod_grupo")
	private String codGrupo;
	
	@Column(name = "cod_clase")
	private String codClase;
	
	@Column(name = "cod_posicion")
	private String codPosicion;
	
	@Column(name = "cod_lado")
	private String codLado;
	
	@Column(name = "grupos")
	private Character grupos;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public Maestro1() {
	}

	public Maestro1(String codArt, String nombre) {
		this.codArt = codArt;
		this.nombre = nombre;
	}

	public Maestro1(String codArt, String nombre, Float minimo, Float maximo, String capacidad, String marca,
			String linea, String medida, String modulo, String clase, String posicion, String lado, String parte,
			Float precio01, Float precio02, Float precio03, Float precio04, Float precio05, Float precio06,
			Float costoQuet, Float costoDola, Float costoDolar, String provee, Float saldoInicial, Float entradas,
			Float salidas, Float costoQA, Float costoDA, Float ulCostoQ, Float ulCostoD, Float tasa, Float ulTasa,
			Date fechUlComp, Date fechCompAnt, Float fobUl, Float fobAnt, Float fleteUl, Float fleteAnt, Float seguroUl,
			Float seguroAnt, Float otrosGastosUl, Float otrosGastosAnt, Float codigoBarras, String codigoAlterno,
			String codigoAnterior, String diam, String long_, Float cantidadXCaja, Float cnt, Float pesoXPiesas,
			Float precioOferta, Date fechaInicio, Date fechaFinal, Float cosDepre, Float costoCif, Float gastos,
			Float existe, String garantia, String grupo, String descripcion, Float desc01, Float desc02, Float desc03,
			String codMarca, String codLinea, String codModulo, String codGrupo, String codClase, String codPosicion,
			String codLado, Character grupos, Character statReg, String usuario, Date fechaIngreso) {
		this.codArt = codArt;
		this.nombre = nombre;
		this.minimo = minimo;
		this.maximo = maximo;
		this.capacidad = capacidad;
		this.marca = marca;
		this.linea = linea;
		this.medida = medida;
		this.modulo = modulo;
		this.clase = clase;
		this.posicion = posicion;
		this.lado = lado;
		this.parte = parte;
		this.precio01 = precio01;
		this.precio02 = precio02;
		this.precio03 = precio03;
		this.precio04 = precio04;
		this.precio05 = precio05;
		this.precio06 = precio06;
		this.costoQuet = costoQuet;
		this.costoDola = costoDola;
		this.costoDolar = costoDolar;
		this.provee = provee;
		this.saldoInicial = saldoInicial;
		this.entradas = entradas;
		this.salidas = salidas;
		this.costoQA = costoQA;
		this.costoDA = costoDA;
		this.ulCostoQ = ulCostoQ;
		this.ulCostoD = ulCostoD;
		this.tasa = tasa;
		this.ulTasa = ulTasa;
		this.fechUlComp = fechUlComp;
		this.fechCompAnt = fechCompAnt;
		this.fobUl = fobUl;
		this.fobAnt = fobAnt;
		this.fleteUl = fleteUl;
		this.fleteAnt = fleteAnt;
		this.seguroUl = seguroUl;
		this.seguroAnt = seguroAnt;
		this.otrosGastosUl = otrosGastosUl;
		this.otrosGastosAnt = otrosGastosAnt;
		this.codigoBarras = codigoBarras;
		this.codigoAlterno = codigoAlterno;
		this.codigoAnterior = codigoAnterior;
		this.diam = diam;
		this.long_ = long_;
		this.cantidadXCaja = cantidadXCaja;
		this.cnt = cnt;
		this.pesoXPiesas = pesoXPiesas;
		this.precioOferta = precioOferta;
		this.fechaInicio = fechaInicio;
		this.fechaFinal = fechaFinal;
		this.cosDepre = cosDepre;
		this.costoCif = costoCif;
		this.gastos = gastos;
		this.existe = existe;
		this.garantia = garantia;
		this.grupo = grupo;
		this.descripcion = descripcion;
		this.desc01 = desc01;
		this.desc02 = desc02;
		this.desc03 = desc03;
		this.codMarca = codMarca;
		this.codLinea = codLinea;
		this.codModulo = codModulo;
		this.codGrupo = codGrupo;
		this.codClase = codClase;
		this.codPosicion = codPosicion;
		this.codLado = codLado;
		this.grupos = grupos;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getCodArt() {
		return this.codArt;
	}

	public void setCodArt(String codArt) {
		this.codArt = codArt;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Float getMinimo() {
		return this.minimo;
	}

	public void setMinimo(Float minimo) {
		this.minimo = minimo;
	}

	public Float getMaximo() {
		return this.maximo;
	}

	public void setMaximo(Float maximo) {
		this.maximo = maximo;
	}

	public String getCapacidad() {
		return this.capacidad;
	}

	public void setCapacidad(String capacidad) {
		this.capacidad = capacidad;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getLinea() {
		return this.linea;
	}

	public void setLinea(String linea) {
		this.linea = linea;
	}

	public String getMedida() {
		return this.medida;
	}

	public void setMedida(String medida) {
		this.medida = medida;
	}

	public String getModulo() {
		return this.modulo;
	}

	public void setModulo(String modulo) {
		this.modulo = modulo;
	}

	public String getClase() {
		return this.clase;
	}

	public void setClase(String clase) {
		this.clase = clase;
	}

	public String getPosicion() {
		return this.posicion;
	}

	public void setPosicion(String posicion) {
		this.posicion = posicion;
	}

	public String getLado() {
		return this.lado;
	}

	public void setLado(String lado) {
		this.lado = lado;
	}

	public String getParte() {
		return this.parte;
	}

	public void setParte(String parte) {
		this.parte = parte;
	}

	public Float getPrecio01() {
		return this.precio01;
	}

	public void setPrecio01(Float precio01) {
		this.precio01 = precio01;
	}

	public Float getPrecio02() {
		return this.precio02;
	}

	public void setPrecio02(Float precio02) {
		this.precio02 = precio02;
	}

	public Float getPrecio03() {
		return this.precio03;
	}

	public void setPrecio03(Float precio03) {
		this.precio03 = precio03;
	}

	public Float getPrecio04() {
		return this.precio04;
	}

	public void setPrecio04(Float precio04) {
		this.precio04 = precio04;
	}

	public Float getPrecio05() {
		return this.precio05;
	}

	public void setPrecio05(Float precio05) {
		this.precio05 = precio05;
	}

	public Float getPrecio06() {
		return this.precio06;
	}

	public void setPrecio06(Float precio06) {
		this.precio06 = precio06;
	}

	public Float getCostoQuet() {
		return this.costoQuet;
	}

	public void setCostoQuet(Float costoQuet) {
		this.costoQuet = costoQuet;
	}

	public Float getCostoDola() {
		return this.costoDola;
	}

	public void setCostoDola(Float costoDola) {
		this.costoDola = costoDola;
	}

	public Float getCostoDolar() {
		return this.costoDolar;
	}

	public void setCostoDolar(Float costoDolar) {
		this.costoDolar = costoDolar;
	}

	public String getProvee() {
		return this.provee;
	}

	public void setProvee(String provee) {
		this.provee = provee;
	}

	public Float getSaldoInicial() {
		return this.saldoInicial;
	}

	public void setSaldoInicial(Float saldoInicial) {
		this.saldoInicial = saldoInicial;
	}

	public Float getEntradas() {
		return this.entradas;
	}

	public void setEntradas(Float entradas) {
		this.entradas = entradas;
	}

	public Float getSalidas() {
		return this.salidas;
	}

	public void setSalidas(Float salidas) {
		this.salidas = salidas;
	}

	public Float getCostoQA() {
		return this.costoQA;
	}

	public void setCostoQA(Float costoQA) {
		this.costoQA = costoQA;
	}

	public Float getCostoDA() {
		return this.costoDA;
	}

	public void setCostoDA(Float costoDA) {
		this.costoDA = costoDA;
	}

	public Float getUlCostoQ() {
		return this.ulCostoQ;
	}

	public void setUlCostoQ(Float ulCostoQ) {
		this.ulCostoQ = ulCostoQ;
	}

	public Float getUlCostoD() {
		return this.ulCostoD;
	}

	public void setUlCostoD(Float ulCostoD) {
		this.ulCostoD = ulCostoD;
	}

	public Float getTasa() {
		return this.tasa;
	}

	public void setTasa(Float tasa) {
		this.tasa = tasa;
	}

	public Float getUlTasa() {
		return this.ulTasa;
	}

	public void setUlTasa(Float ulTasa) {
		this.ulTasa = ulTasa;
	}

	public Date getFechUlComp() {
		return this.fechUlComp;
	}

	public void setFechUlComp(Date fechUlComp) {
		this.fechUlComp = fechUlComp;
	}

	public Date getFechCompAnt() {
		return this.fechCompAnt;
	}

	public void setFechCompAnt(Date fechCompAnt) {
		this.fechCompAnt = fechCompAnt;
	}

	public Float getFobUl() {
		return this.fobUl;
	}

	public void setFobUl(Float fobUl) {
		this.fobUl = fobUl;
	}

	public Float getFobAnt() {
		return this.fobAnt;
	}

	public void setFobAnt(Float fobAnt) {
		this.fobAnt = fobAnt;
	}

	public Float getFleteUl() {
		return this.fleteUl;
	}

	public void setFleteUl(Float fleteUl) {
		this.fleteUl = fleteUl;
	}

	public Float getFleteAnt() {
		return this.fleteAnt;
	}

	public void setFleteAnt(Float fleteAnt) {
		this.fleteAnt = fleteAnt;
	}

	public Float getSeguroUl() {
		return this.seguroUl;
	}

	public void setSeguroUl(Float seguroUl) {
		this.seguroUl = seguroUl;
	}

	public Float getSeguroAnt() {
		return this.seguroAnt;
	}

	public void setSeguroAnt(Float seguroAnt) {
		this.seguroAnt = seguroAnt;
	}

	public Float getOtrosGastosUl() {
		return this.otrosGastosUl;
	}

	public void setOtrosGastosUl(Float otrosGastosUl) {
		this.otrosGastosUl = otrosGastosUl;
	}

	public Float getOtrosGastosAnt() {
		return this.otrosGastosAnt;
	}

	public void setOtrosGastosAnt(Float otrosGastosAnt) {
		this.otrosGastosAnt = otrosGastosAnt;
	}

	public Float getCodigoBarras() {
		return this.codigoBarras;
	}

	public void setCodigoBarras(Float codigoBarras) {
		this.codigoBarras = codigoBarras;
	}

	public String getCodigoAlterno() {
		return this.codigoAlterno;
	}

	public void setCodigoAlterno(String codigoAlterno) {
		this.codigoAlterno = codigoAlterno;
	}

	public String getCodigoAnterior() {
		return this.codigoAnterior;
	}

	public void setCodigoAnterior(String codigoAnterior) {
		this.codigoAnterior = codigoAnterior;
	}

	public String getDiam() {
		return this.diam;
	}

	public void setDiam(String diam) {
		this.diam = diam;
	}

	public String getLong_() {
		return this.long_;
	}

	public void setLong_(String long_) {
		this.long_ = long_;
	}

	public Float getCantidadXCaja() {
		return this.cantidadXCaja;
	}

	public void setCantidadXCaja(Float cantidadXCaja) {
		this.cantidadXCaja = cantidadXCaja;
	}

	public Float getCnt() {
		return this.cnt;
	}

	public void setCnt(Float cnt) {
		this.cnt = cnt;
	}

	public Float getPesoXPiesas() {
		return this.pesoXPiesas;
	}

	public void setPesoXPiesas(Float pesoXPiesas) {
		this.pesoXPiesas = pesoXPiesas;
	}

	public Float getPrecioOferta() {
		return this.precioOferta;
	}

	public void setPrecioOferta(Float precioOferta) {
		this.precioOferta = precioOferta;
	}

	public Date getFechaInicio() {
		return this.fechaInicio;
	}

	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}

	public Date getFechaFinal() {
		return this.fechaFinal;
	}

	public void setFechaFinal(Date fechaFinal) {
		this.fechaFinal = fechaFinal;
	}

	public Float getCosDepre() {
		return this.cosDepre;
	}

	public void setCosDepre(Float cosDepre) {
		this.cosDepre = cosDepre;
	}

	public Float getCostoCif() {
		return this.costoCif;
	}

	public void setCostoCif(Float costoCif) {
		this.costoCif = costoCif;
	}

	public Float getGastos() {
		return this.gastos;
	}

	public void setGastos(Float gastos) {
		this.gastos = gastos;
	}

	public Float getExiste() {
		return this.existe;
	}

	public void setExiste(Float existe) {
		this.existe = existe;
	}

	public String getGarantia() {
		return this.garantia;
	}

	public void setGarantia(String garantia) {
		this.garantia = garantia;
	}

	public String getGrupo() {
		return this.grupo;
	}

	public void setGrupo(String grupo) {
		this.grupo = grupo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Float getDesc01() {
		return this.desc01;
	}

	public void setDesc01(Float desc01) {
		this.desc01 = desc01;
	}

	public Float getDesc02() {
		return this.desc02;
	}

	public void setDesc02(Float desc02) {
		this.desc02 = desc02;
	}

	public Float getDesc03() {
		return this.desc03;
	}

	public void setDesc03(Float desc03) {
		this.desc03 = desc03;
	}

	public String getCodMarca() {
		return this.codMarca;
	}

	public void setCodMarca(String codMarca) {
		this.codMarca = codMarca;
	}

	public String getCodLinea() {
		return this.codLinea;
	}

	public void setCodLinea(String codLinea) {
		this.codLinea = codLinea;
	}

	public String getCodModulo() {
		return this.codModulo;
	}

	public void setCodModulo(String codModulo) {
		this.codModulo = codModulo;
	}

	public String getCodGrupo() {
		return this.codGrupo;
	}

	public void setCodGrupo(String codGrupo) {
		this.codGrupo = codGrupo;
	}

	public String getCodClase() {
		return this.codClase;
	}

	public void setCodClase(String codClase) {
		this.codClase = codClase;
	}

	public String getCodPosicion() {
		return this.codPosicion;
	}

	public void setCodPosicion(String codPosicion) {
		this.codPosicion = codPosicion;
	}

	public String getCodLado() {
		return this.codLado;
	}

	public void setCodLado(String codLado) {
		this.codLado = codLado;
	}

	public Character getGrupos() {
		return this.grupos;
	}

	public void setGrupos(Character grupos) {
		this.grupos = grupos;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
