package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Marcas generated by hbm2java
 */
@Entity
@Table(name = "marcas")
public class Marcas implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "cod_familia")
	private String codFamilia;
	
	@Column(name = "cod_marca")
	private String codMarca;
	
	@Column(name = "marcas")
	private String marcas;
	
	@Column(name = "cod_marca1")
	private String codMarca1;
	
	@Column(name = "id_tipo")
	private String idTipo;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public Marcas() {
	}

	public Marcas(String codFamilia, String codMarca, String marcas, String codMarca1, String idTipo, Character statReg,
			String usuario, Date fechaIngreso) {
		this.codFamilia = codFamilia;
		this.codMarca = codMarca;
		this.marcas = marcas;
		this.codMarca1 = codMarca1;
		this.idTipo = idTipo;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getCodFamilia() {
		return this.codFamilia;
	}

	public void setCodFamilia(String codFamilia) {
		this.codFamilia = codFamilia;
	}

	public String getCodMarca() {
		return this.codMarca;
	}

	public void setCodMarca(String codMarca) {
		this.codMarca = codMarca;
	}

	public String getMarcas() {
		return this.marcas;
	}

	public void setMarcas(String marcas) {
		this.marcas = marcas;
	}

	public String getCodMarca1() {
		return this.codMarca1;
	}

	public void setCodMarca1(String codMarca1) {
		this.codMarca1 = codMarca1;
	}

	public String getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(String idTipo) {
		this.idTipo = idTipo;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
