package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Mecanismo generated by hbm2java
 */
@Entity
@Table(name = "mecanismo")
public class Mecanismo implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "cod_mecanismo")
	private String codMecanismo;
	
	@Column(name = "descrip_meca")
	private String descripMeca;
	
	@Column(name = "observaciones")
	private String observaciones;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public Mecanismo() {
	}

	public Mecanismo(String codMecanismo, String descripMeca, String observaciones, Character statReg, String usuario,
			Date fechaIngreso) {
		this.codMecanismo = codMecanismo;
		this.descripMeca = descripMeca;
		this.observaciones = observaciones;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getCodMecanismo() {
		return this.codMecanismo;
	}

	public void setCodMecanismo(String codMecanismo) {
		this.codMecanismo = codMecanismo;
	}

	public String getDescripMeca() {
		return this.descripMeca;
	}

	public void setDescripMeca(String descripMeca) {
		this.descripMeca = descripMeca;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
