package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * MTipo generated by hbm2java
 */
@Entity
@Table(name = "m_tipo")
public class MTipo implements java.io.Serializable {

	@Id
	@Column(name = "id_m_tipo")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idMTipo;
	
	@Column(name = "codigo")
	private String codigo;
	
	@Column(name = "concepto")
	private String concepto;

	public MTipo() {
	}

	public MTipo(String codigo) {
		this.codigo = codigo;
	}

	public MTipo(String codigo, String concepto) {
		this.codigo = codigo;
		this.concepto = concepto;
	}

	public Long getIdMTipo() {
		return this.idMTipo;
	}

	public void setIdMTipo(Long idMTipo) {
		this.idMTipo = idMTipo;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

}
