package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Posicion generated by hbm2java
 */
@Entity
@Table(name = "posicion")
public class Posicion implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "cod_posicion")
	private String codPosicion;
	
	@Column(name = "descrip_pos")
	private String descripPos;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public Posicion() {
	}

	public Posicion(String codPosicion, String descripPos, Character statReg, String usuario, Date fechaIngreso) {
		this.codPosicion = codPosicion;
		this.descripPos = descripPos;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getCodPosicion() {
		return this.codPosicion;
	}

	public void setCodPosicion(String codPosicion) {
		this.codPosicion = codPosicion;
	}

	public String getDescripPos() {
		return this.descripPos;
	}

	public void setDescripPos(String descripPos) {
		this.descripPos = descripPos;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
