package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Provee generated by hbm2java
 */
@Entity
@Table(name = "provee")
public class Provee implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "codigo")
	private String codigo;
	
	@Column(name = "nombre")
	private String nombre;
	
	@Column(name = "direccion")
	private String direccion;
	
	@Column(name = "telefono")
	private String telefono;
	
	@Column(name = "contacto")
	private String contacto;
	
	@Column(name = "telex")
	private String telex;
	
	@Column(name = "fax")
	private String fax;
	
	@Column(name = "ciudad")
	private String ciudad;
	
	@Column(name = "nit")
	private String nit;
	
	@Column(name = "lugarprocede")
	private String lugarProcede;
	
	@Column(name = "saldoinicial")
	private Float saldoInicial;
	
	@Column(name = "cargos")
	private Float cargos;
	
	@Column(name = "abonos")
	private Float abonos;
	
	@Column(name = "observaciones")
	private String observaciones;
	
	@Column(name = "diascredito")
	private Integer diasCredito;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public Provee() {
	}

	public Provee(String codigo, String nombre, String direccion, String telefono, String contacto, String telex,
			String fax, String ciudad, String nit, String lugarProcede, Float saldoInicial, Float cargos, Float abonos,
			String observaciones, Integer diasCredito, Character statReg, String usuario, Date fechaIngreso) {
		this.codigo = codigo;
		this.nombre = nombre;
		this.direccion = direccion;
		this.telefono = telefono;
		this.contacto = contacto;
		this.telex = telex;
		this.fax = fax;
		this.ciudad = ciudad;
		this.nit = nit;
		this.lugarProcede = lugarProcede;
		this.saldoInicial = saldoInicial;
		this.cargos = cargos;
		this.abonos = abonos;
		this.observaciones = observaciones;
		this.diasCredito = diasCredito;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getContacto() {
		return this.contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	public String getTelex() {
		return this.telex;
	}

	public void setTelex(String telex) {
		this.telex = telex;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getNit() {
		return this.nit;
	}

	public void setNit(String nit) {
		this.nit = nit;
	}

	public String getLugarProcede() {
		return this.lugarProcede;
	}

	public void setLugarProcede(String lugarProcede) {
		this.lugarProcede = lugarProcede;
	}

	public Float getSaldoInicial() {
		return this.saldoInicial;
	}

	public void setSaldoInicial(Float saldoInicial) {
		this.saldoInicial = saldoInicial;
	}

	public Float getCargos() {
		return this.cargos;
	}

	public void setCargos(Float cargos) {
		this.cargos = cargos;
	}

	public Float getAbonos() {
		return this.abonos;
	}

	public void setAbonos(Float abonos) {
		this.abonos = abonos;
	}

	public String getObservaciones() {
		return this.observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public Integer getDiasCredito() {
		return this.diasCredito;
	}

	public void setDiasCredito(Integer diasCredito) {
		this.diasCredito = diasCredito;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
