package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Repuesto generated by hbm2java
 */
@Entity
@Table(name = "repuesto")
public class Repuesto implements java.io.Serializable {

	@Id
	@Column(name = "id_rep")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idRep;
	
	@Column(name = "id_repuesto")
	private String idRepuesto;
	
	@Column(name = "pieza")
	private String pieza;
	
	@Column(name = "id_grupo")
	private Short idGrupo;
	
	@Column(name = "id_tipo")
	private Short idTipo;

	public Repuesto() {
	}

	public Repuesto(String idRepuesto, String pieza, Short idGrupo, Short idTipo) {
		this.idRepuesto = idRepuesto;
		this.pieza = pieza;
		this.idGrupo = idGrupo;
		this.idTipo = idTipo;
	}

	public Long getIdRep() {
		return this.idRep;
	}

	public void setIdRep(Long idRep) {
		this.idRep = idRep;
	}

	public String getIdRepuesto() {
		return this.idRepuesto;
	}

	public void setIdRepuesto(String idRepuesto) {
		this.idRepuesto = idRepuesto;
	}

	public String getPieza() {
		return this.pieza;
	}

	public void setPieza(String pieza) {
		this.pieza = pieza;
	}

	public Short getIdGrupo() {
		return this.idGrupo;
	}

	public void setIdGrupo(Short idGrupo) {
		this.idGrupo = idGrupo;
	}

	public Short getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(Short idTipo) {
		this.idTipo = idTipo;
	}

}
