package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RequisicionH generated by hbm2java
 */
@Entity
@Table(name = "requisicion_h")
public class RequisicionH implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "vendedor")
	private String vendedor;
	
	@Column(name = "entrega")
	private String entrega;
	
	@Column(name = "numini")
	private String numIni;
	
	@Column(name = "numfin")
	private String numFin;
	
	@Column(name = "cantidad")
	private Float cantidad;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;
	
	@Column(name = "fecha_inactiva")
	private Date fechaInactiva;

	public RequisicionH() {
	}

	public RequisicionH(String vendedor, String entrega, String numIni, String numFin, Float cantidad,
			Character statReg, String usuario, Date fechaIngreso, Date fechaInactiva) {
		this.vendedor = vendedor;
		this.entrega = entrega;
		this.numIni = numIni;
		this.numFin = numFin;
		this.cantidad = cantidad;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
		this.fechaInactiva = fechaInactiva;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(String vendedor) {
		this.vendedor = vendedor;
	}

	public String getEntrega() {
		return this.entrega;
	}

	public void setEntrega(String entrega) {
		this.entrega = entrega;
	}

	public String getNumIni() {
		return this.numIni;
	}

	public void setNumIni(String numIni) {
		this.numIni = numIni;
	}

	public String getNumFin() {
		return this.numFin;
	}

	public void setNumFin(String numFin) {
		this.numFin = numFin;
	}

	public Float getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Float cantidad) {
		this.cantidad = cantidad;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

	public Date getFechaInactiva() {
		return this.fechaInactiva;
	}

	public void setFechaInactiva(Date fechaInactiva) {
		this.fechaInactiva = fechaInactiva;
	}

}
