package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * RequisicionD generated by hbm2java
 */
@Entity
@Table(name = "requisicion_d")
public class RequisicionD implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "vendedor")
	private String vendedor;
	
	@Column(name = "numreq")
	private String numReq;
	
	@Column(name = "docum")
	private String docum;
	
	@Column(name = "operada")
	private String operada;
	
	@Column(name = "fecha_operada")
	private Date fechaOperada;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public RequisicionD() {
	}

	public RequisicionD(String vendedor, String numReq, String docum, String operada, Date fechaOperada,
			Character statReg, String usuario, Date fechaIngreso) {
		this.vendedor = vendedor;
		this.numReq = numReq;
		this.docum = docum;
		this.operada = operada;
		this.fechaOperada = fechaOperada;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getVendedor() {
		return this.vendedor;
	}

	public void setVendedor(String vendedor) {
		this.vendedor = vendedor;
	}

	public String getNumReq() {
		return this.numReq;
	}

	public void setNumReq(String numReq) {
		this.numReq = numReq;
	}

	public String getDocum() {
		return this.docum;
	}

	public void setDocum(String docum) {
		this.docum = docum;
	}

	public String getOperada() {
		return this.operada;
	}

	public void setOperada(String operada) {
		this.operada = operada;
	}

	public Date getFechaOperada() {
		return this.fechaOperada;
	}

	public void setFechaOperada(Date fechaOperada) {
		this.fechaOperada = fechaOperada;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
