package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Similaridad generated by hbm2java
 */
@Entity
@Table(name = "similaridad")
public class Similaridad implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "id_similaridad")
	private String idSimilaridad;
	
	@Column(name = "nombre_linea")
	private String nombreLinea;
	
	@Column(name = "id_linea")
	private String idLinea;
	
	@Column(name = "anios")
	private String anios;
	
	@Column(name = "anios_ini")
	private String anioIni;
	
	@Column(name = "anio_fin")
	private String anioFin;
	
	@Column(name = "stat_reg")
	private Character statReg;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "fecha_ingreso")
	private Date fechaIngreso;

	public Similaridad() {
	}

	public Similaridad(String idSimilaridad, String nombreLinea, String idLinea, String anios, String anioIni,
			String anioFin, Character statReg, String usuario, Date fechaIngreso) {
		this.idSimilaridad = idSimilaridad;
		this.nombreLinea = nombreLinea;
		this.idLinea = idLinea;
		this.anios = anios;
		this.anioIni = anioIni;
		this.anioFin = anioFin;
		this.statReg = statReg;
		this.usuario = usuario;
		this.fechaIngreso = fechaIngreso;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getIdSimilaridad() {
		return this.idSimilaridad;
	}

	public void setIdSimilaridad(String idSimilaridad) {
		this.idSimilaridad = idSimilaridad;
	}

	public String getNombreLinea() {
		return this.nombreLinea;
	}

	public void setNombreLinea(String nombreLinea) {
		this.nombreLinea = nombreLinea;
	}

	public String getIdLinea() {
		return this.idLinea;
	}

	public void setIdLinea(String idLinea) {
		this.idLinea = idLinea;
	}

	public String getAnios() {
		return this.anios;
	}

	public void setAnios(String anios) {
		this.anios = anios;
	}

	public String getAnioIni() {
		return this.anioIni;
	}

	public void setAnioIni(String anioIni) {
		this.anioIni = anioIni;
	}

	public String getAnioFin() {
		return this.anioFin;
	}

	public void setAnioFin(String anioFin) {
		this.anioFin = anioFin;
	}

	public Character getStatReg() {
		return this.statReg;
	}

	public void setStatReg(Character statReg) {
		this.statReg = statReg;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Date getFechaIngreso() {
		return this.fechaIngreso;
	}

	public void setFechaIngreso(Date fechaIngreso) {
		this.fechaIngreso = fechaIngreso;
	}

}
