package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Subgrupos generated by hbm2java
 */
@Entity
@Table(name = "subgrupos")
public class SubGrupos implements java.io.Serializable {

	@Id
	@Column(name = "id_subgrupos")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idSubGrupos;
	
	@Column(name = "subgrupos")
	private String subGrupos;

	public SubGrupos() {
	}

	public SubGrupos(String subGrupos) {
		this.subGrupos = subGrupos;
	}

	public Long getIdSubGrupos() {
		return this.idSubGrupos;
	}

	public void setIdSubGrupos(Long idSubGrupos) {
		this.idSubGrupos = idSubGrupos;
	}

	public String getSubGrupos() {
		return this.subGrupos;
	}

	public void setSubGrupos(String subGrupos) {
		this.subGrupos = subGrupos;
	}

}
