package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Unidad generated by hbm2java
 */
@Entity
@Table(name = "unidad")
public class Unidad implements java.io.Serializable {

	@Id
	@Column(name = "id_unidad")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long idUnidad;
	
	@Column(name = "codigo")
	private String codigo;
	
	@Column(name = "concepto")
	private String concepto;

	public Unidad() {
	}

	public Unidad(String codigo) {
		this.codigo = codigo;
	}

	public Unidad(String codigo, String concepto) {
		this.codigo = codigo;
		this.concepto = concepto;
	}

	public Long getIdUnidad() {
		return this.idUnidad;
	}

	public void setIdUnidad(Long idUnidad) {
		this.idUnidad = idUnidad;
	}

	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	public String getConcepto() {
		return this.concepto;
	}

	public void setConcepto(String concepto) {
		this.concepto = concepto;
	}

}
