package com.scm.gsoft.domain.inv;
// Generated 26/08/2018 02:38:20 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

	@Id
	@Column(name = "cia")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long cia;
	
	@Column(name = "usuario")
	private String usuario;
	
	@Column(name = "clave")
	private String clave;
	
	@Column(name = "extra")
	private String extra;
	
	@Column(name = "o01mant")
	private boolean o01mant;
	
	@Column(name = "o02mant")
	private boolean o02mant;
	
	@Column(name = "o03mant")
	private boolean o03mant;
	
	@Column(name = "o04mant")
	private boolean o04mant;
	
	@Column(name = "o05mant")
	private boolean o05mant;
	
	@Column(name = "o06mant")
	private boolean o06mant;
	
	@Column(name = "o07mant")
	private boolean o07mant;
	
	@Column(name = "o08mant")
	private boolean o08mant;
	
	@Column(name = "o09mant")
	private boolean o09mant;
	
	@Column(name = "o10mant")
	private boolean o10mant;
	
	@Column(name = "o01mov")
	private boolean o01mov;
	
	@Column(name = "o02mov")
	private boolean o02mov;
	
	@Column(name = "o03mov")
	private boolean o03mov;
	
	@Column(name = "o04mov")
	private boolean o04mov;
	
	@Column(name = "o05mov")
	private boolean o05mov;
		
	@Column(name = "o06mov")
	private boolean o06mov;
	
	@Column(name = "o07mov")
	private boolean o07mov;
	
	@Column(name = "o08mov")
	private boolean o08mov;
	
	@Column(name = "o09mov")
	private boolean o09mov;
	
	@Column(name = "o10mov")
	private boolean o10mov;
	
	@Column(name = "o11mov")
	private boolean o11mov;
	
	@Column(name = "o12mov")
	private boolean o12mov;
	
	@Column(name = "o11mant")
	private boolean o11mant;
	
	@Column(name = "o12mant")
	private boolean o12mant;
	
	@Column(name = "o13mant")
	private boolean o13mant;
	
	@Column(name = "o14mant")
	private boolean o14mant;
	
	@Column(name = "o15mant")
	private boolean o15mant;
	
	@Column(name = "o01consul")
	private boolean o01consul;
	
	@Column(name = "o02consul")
	private boolean o02consul;
	
	@Column(name = "o03consul")
	private boolean o03consul;
	
	@Column(name = "o04consul")
	private boolean o04consul;
	
	@Column(name = "o05consul")
	private boolean o05consul;
	
	@Column(name = "o06consul")
	private boolean o06consul;
	
	@Column(name = "o07consul")
	private boolean o07consul;
	
	@Column(name = "o08consul")
	private boolean o08consul;
	
	@Column(name = "o09consul")
	private boolean o09consul;
	
	@Column(name = "o10consul")
	private boolean o10consul;
	
	@Column(name = "o01rep")
	private boolean o01rep;
	
	@Column(name = "o02rep")
	private boolean o02rep;
	
	@Column(name = "o03rep")
	private boolean o03rep;
	
	@Column(name = "o04rep")
	private boolean o04rep;
	
	@Column(name = "o05rep")
	private boolean o05rep;
	
	@Column(name = "o06rep")
	private boolean o06rep;
	
	@Column(name = "o07rep")
	private boolean o07rep;
	
	@Column(name = "o08rep")
	private boolean o08rep;
	
	@Column(name = "o09rep")
	private boolean o09rep;
	
	@Column(name = "o10rep")
	private boolean o10rep;
	
	@Column(name = "o11rep")
	private boolean o11rep;
	
	@Column(name = "o12rep")
	private boolean o12rep;
	
	@Column(name = "o01pror")
	private boolean o01pror;
	
	@Column(name = "o02pror")
	private boolean o02pror;
	
	@Column(name = "o03pror")
	private boolean o03pror;
	
	@Column(name = "o04pror")
	private boolean o04pror;
	
	@Column(name = "o01herra")
	private boolean o01herra;
	
	@Column(name = "o02herra")
	private boolean o02herra;
	
	@Column(name = "o03herra")
	private boolean o03herra;
	
	@Column(name = "o04herra")
	private boolean o04herra;
	
	@Column(name = "o05herra")
	private boolean o05herra;
	
	@Column(name = "o06herra")
	private boolean o06herra;
	
	@Column(name = "o07herra")
	private boolean o07herra;
	
	@Column(name = "o08herra")
	private boolean o08herra;
	
	@Column(name = "o09herra")
	private boolean o09herra;
	
	@Column(name = "o10herra")
	private boolean o10herra;
	
	@Column(name = "acceso01")
	private boolean acceso01;
	
	@Column(name = "acceso02")
	private boolean acceso02;
	
	@Column(name = "acceso03")
	private boolean acceso03;
	
	@Column(name = "acceso04")
	private boolean acceso04;
	
	@Column(name = "acceso05")
	private boolean acceso05;
	
	@Column(name = "acceso06")
	private boolean acceso06;
	
	@Column(name = "acceso07")
	private boolean acceso07;
	
	@Column(name = "acceso08")
	private boolean acceso08;
	
	@Column(name = "acceso09")
	private boolean acceso09;
	
	@Column(name = "acceso10")
	private boolean acceso10;
	
	@Column(name = "acceso11")
	private boolean acceso11;
	
	@Column(name = "acceso12")
	private boolean acceso12;
	
	@Column(name = "acceso13")
	private boolean acceso13;
	
	@Column(name = "acceso14")
	private boolean acceso14;
	
	@Column(name = "acceso15")
	private boolean acceso15;

	public Usuario() {
	}

	public Usuario(String usuario, String clave, boolean o01mant, boolean o02mant, boolean o03mant, boolean o04mant,
			boolean o05mant, boolean o06mant, boolean o07mant, boolean o08mant, boolean o09mant, boolean o10mant,
			boolean o01mov, boolean o02mov, boolean o03mov, boolean o04mov, boolean o05mov, boolean o06mov,
			boolean o07mov, boolean o08mov, boolean o09mov, boolean o10mov, boolean o11mov, boolean o12mov,
			boolean o11mant, boolean o12mant, boolean o13mant, boolean o14mant, boolean o15mant, boolean o01consul,
			boolean o02consul, boolean o03consul, boolean o04consul, boolean o05consul, boolean o06consul,
			boolean o07consul, boolean o08consul, boolean o09consul, boolean o10consul, boolean o01rep, boolean o02rep,
			boolean o03rep, boolean o04rep, boolean o05rep, boolean o06rep, boolean o07rep, boolean o08rep,
			boolean o09rep, boolean o10rep, boolean o11rep, boolean o12rep, boolean o01pror, boolean o02pror,
			boolean o03pror, boolean o04pror, boolean o01herra, boolean o02herra, boolean o03herra, boolean o04herra,
			boolean o05herra, boolean o06herra, boolean o07herra, boolean o08herra, boolean o09herra, boolean o10herra,
			boolean acceso01, boolean acceso02, boolean acceso03, boolean acceso04, boolean acceso05, boolean acceso06,
			boolean acceso07, boolean acceso08, boolean acceso09, boolean acceso10, boolean acceso11, boolean acceso12,
			boolean acceso13, boolean acceso14, boolean acceso15) {
		this.usuario = usuario;
		this.clave = clave;
		this.o01mant = o01mant;
		this.o02mant = o02mant;
		this.o03mant = o03mant;
		this.o04mant = o04mant;
		this.o05mant = o05mant;
		this.o06mant = o06mant;
		this.o07mant = o07mant;
		this.o08mant = o08mant;
		this.o09mant = o09mant;
		this.o10mant = o10mant;
		this.o01mov = o01mov;
		this.o02mov = o02mov;
		this.o03mov = o03mov;
		this.o04mov = o04mov;
		this.o05mov = o05mov;
		this.o06mov = o06mov;
		this.o07mov = o07mov;
		this.o08mov = o08mov;
		this.o09mov = o09mov;
		this.o10mov = o10mov;
		this.o11mov = o11mov;
		this.o12mov = o12mov;
		this.o11mant = o11mant;
		this.o12mant = o12mant;
		this.o13mant = o13mant;
		this.o14mant = o14mant;
		this.o15mant = o15mant;
		this.o01consul = o01consul;
		this.o02consul = o02consul;
		this.o03consul = o03consul;
		this.o04consul = o04consul;
		this.o05consul = o05consul;
		this.o06consul = o06consul;
		this.o07consul = o07consul;
		this.o08consul = o08consul;
		this.o09consul = o09consul;
		this.o10consul = o10consul;
		this.o01rep = o01rep;
		this.o02rep = o02rep;
		this.o03rep = o03rep;
		this.o04rep = o04rep;
		this.o05rep = o05rep;
		this.o06rep = o06rep;
		this.o07rep = o07rep;
		this.o08rep = o08rep;
		this.o09rep = o09rep;
		this.o10rep = o10rep;
		this.o11rep = o11rep;
		this.o12rep = o12rep;
		this.o01pror = o01pror;
		this.o02pror = o02pror;
		this.o03pror = o03pror;
		this.o04pror = o04pror;
		this.o01herra = o01herra;
		this.o02herra = o02herra;
		this.o03herra = o03herra;
		this.o04herra = o04herra;
		this.o05herra = o05herra;
		this.o06herra = o06herra;
		this.o07herra = o07herra;
		this.o08herra = o08herra;
		this.o09herra = o09herra;
		this.o10herra = o10herra;
		this.acceso01 = acceso01;
		this.acceso02 = acceso02;
		this.acceso03 = acceso03;
		this.acceso04 = acceso04;
		this.acceso05 = acceso05;
		this.acceso06 = acceso06;
		this.acceso07 = acceso07;
		this.acceso08 = acceso08;
		this.acceso09 = acceso09;
		this.acceso10 = acceso10;
		this.acceso11 = acceso11;
		this.acceso12 = acceso12;
		this.acceso13 = acceso13;
		this.acceso14 = acceso14;
		this.acceso15 = acceso15;
	}

	public Usuario(String usuario, String clave, String extra, boolean o01mant, boolean o02mant, boolean o03mant,
			boolean o04mant, boolean o05mant, boolean o06mant, boolean o07mant, boolean o08mant, boolean o09mant,
			boolean o10mant, boolean o01mov, boolean o02mov, boolean o03mov, boolean o04mov, boolean o05mov,
			boolean o06mov, boolean o07mov, boolean o08mov, boolean o09mov, boolean o10mov, boolean o11mov,
			boolean o12mov, boolean o11mant, boolean o12mant, boolean o13mant, boolean o14mant, boolean o15mant,
			boolean o01consul, boolean o02consul, boolean o03consul, boolean o04consul, boolean o05consul,
			boolean o06consul, boolean o07consul, boolean o08consul, boolean o09consul, boolean o10consul,
			boolean o01rep, boolean o02rep, boolean o03rep, boolean o04rep, boolean o05rep, boolean o06rep,
			boolean o07rep, boolean o08rep, boolean o09rep, boolean o10rep, boolean o11rep, boolean o12rep,
			boolean o01pror, boolean o02pror, boolean o03pror, boolean o04pror, boolean o01herra, boolean o02herra,
			boolean o03herra, boolean o04herra, boolean o05herra, boolean o06herra, boolean o07herra, boolean o08herra,
			boolean o09herra, boolean o10herra, boolean acceso01, boolean acceso02, boolean acceso03, boolean acceso04,
			boolean acceso05, boolean acceso06, boolean acceso07, boolean acceso08, boolean acceso09, boolean acceso10,
			boolean acceso11, boolean acceso12, boolean acceso13, boolean acceso14, boolean acceso15) {
		this.usuario = usuario;
		this.clave = clave;
		this.extra = extra;
		this.o01mant = o01mant;
		this.o02mant = o02mant;
		this.o03mant = o03mant;
		this.o04mant = o04mant;
		this.o05mant = o05mant;
		this.o06mant = o06mant;
		this.o07mant = o07mant;
		this.o08mant = o08mant;
		this.o09mant = o09mant;
		this.o10mant = o10mant;
		this.o01mov = o01mov;
		this.o02mov = o02mov;
		this.o03mov = o03mov;
		this.o04mov = o04mov;
		this.o05mov = o05mov;
		this.o06mov = o06mov;
		this.o07mov = o07mov;
		this.o08mov = o08mov;
		this.o09mov = o09mov;
		this.o10mov = o10mov;
		this.o11mov = o11mov;
		this.o12mov = o12mov;
		this.o11mant = o11mant;
		this.o12mant = o12mant;
		this.o13mant = o13mant;
		this.o14mant = o14mant;
		this.o15mant = o15mant;
		this.o01consul = o01consul;
		this.o02consul = o02consul;
		this.o03consul = o03consul;
		this.o04consul = o04consul;
		this.o05consul = o05consul;
		this.o06consul = o06consul;
		this.o07consul = o07consul;
		this.o08consul = o08consul;
		this.o09consul = o09consul;
		this.o10consul = o10consul;
		this.o01rep = o01rep;
		this.o02rep = o02rep;
		this.o03rep = o03rep;
		this.o04rep = o04rep;
		this.o05rep = o05rep;
		this.o06rep = o06rep;
		this.o07rep = o07rep;
		this.o08rep = o08rep;
		this.o09rep = o09rep;
		this.o10rep = o10rep;
		this.o11rep = o11rep;
		this.o12rep = o12rep;
		this.o01pror = o01pror;
		this.o02pror = o02pror;
		this.o03pror = o03pror;
		this.o04pror = o04pror;
		this.o01herra = o01herra;
		this.o02herra = o02herra;
		this.o03herra = o03herra;
		this.o04herra = o04herra;
		this.o05herra = o05herra;
		this.o06herra = o06herra;
		this.o07herra = o07herra;
		this.o08herra = o08herra;
		this.o09herra = o09herra;
		this.o10herra = o10herra;
		this.acceso01 = acceso01;
		this.acceso02 = acceso02;
		this.acceso03 = acceso03;
		this.acceso04 = acceso04;
		this.acceso05 = acceso05;
		this.acceso06 = acceso06;
		this.acceso07 = acceso07;
		this.acceso08 = acceso08;
		this.acceso09 = acceso09;
		this.acceso10 = acceso10;
		this.acceso11 = acceso11;
		this.acceso12 = acceso12;
		this.acceso13 = acceso13;
		this.acceso14 = acceso14;
		this.acceso15 = acceso15;
	}

	public Long getCia() {
		return this.cia;
	}

	public void setCia(Long cia) {
		this.cia = cia;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public String getExtra() {
		return this.extra;
	}

	public void setExtra(String extra) {
		this.extra = extra;
	}

	public boolean isO01mant() {
		return this.o01mant;
	}

	public void setO01mant(boolean o01mant) {
		this.o01mant = o01mant;
	}

	public boolean isO02mant() {
		return this.o02mant;
	}

	public void setO02mant(boolean o02mant) {
		this.o02mant = o02mant;
	}

	public boolean isO03mant() {
		return this.o03mant;
	}

	public void setO03mant(boolean o03mant) {
		this.o03mant = o03mant;
	}

	public boolean isO04mant() {
		return this.o04mant;
	}

	public void setO04mant(boolean o04mant) {
		this.o04mant = o04mant;
	}

	public boolean isO05mant() {
		return this.o05mant;
	}

	public void setO05mant(boolean o05mant) {
		this.o05mant = o05mant;
	}

	public boolean isO06mant() {
		return this.o06mant;
	}

	public void setO06mant(boolean o06mant) {
		this.o06mant = o06mant;
	}

	public boolean isO07mant() {
		return this.o07mant;
	}

	public void setO07mant(boolean o07mant) {
		this.o07mant = o07mant;
	}

	public boolean isO08mant() {
		return this.o08mant;
	}

	public void setO08mant(boolean o08mant) {
		this.o08mant = o08mant;
	}

	public boolean isO09mant() {
		return this.o09mant;
	}

	public void setO09mant(boolean o09mant) {
		this.o09mant = o09mant;
	}

	public boolean isO10mant() {
		return this.o10mant;
	}

	public void setO10mant(boolean o10mant) {
		this.o10mant = o10mant;
	}

	public boolean isO01mov() {
		return this.o01mov;
	}

	public void setO01mov(boolean o01mov) {
		this.o01mov = o01mov;
	}

	public boolean isO02mov() {
		return this.o02mov;
	}

	public void setO02mov(boolean o02mov) {
		this.o02mov = o02mov;
	}

	public boolean isO03mov() {
		return this.o03mov;
	}

	public void setO03mov(boolean o03mov) {
		this.o03mov = o03mov;
	}

	public boolean isO04mov() {
		return this.o04mov;
	}

	public void setO04mov(boolean o04mov) {
		this.o04mov = o04mov;
	}

	public boolean isO05mov() {
		return this.o05mov;
	}

	public void setO05mov(boolean o05mov) {
		this.o05mov = o05mov;
	}

	public boolean isO06mov() {
		return this.o06mov;
	}

	public void setO06mov(boolean o06mov) {
		this.o06mov = o06mov;
	}

	public boolean isO07mov() {
		return this.o07mov;
	}

	public void setO07mov(boolean o07mov) {
		this.o07mov = o07mov;
	}

	public boolean isO08mov() {
		return this.o08mov;
	}

	public void setO08mov(boolean o08mov) {
		this.o08mov = o08mov;
	}

	public boolean isO09mov() {
		return this.o09mov;
	}

	public void setO09mov(boolean o09mov) {
		this.o09mov = o09mov;
	}

	public boolean isO10mov() {
		return this.o10mov;
	}

	public void setO10mov(boolean o10mov) {
		this.o10mov = o10mov;
	}

	public boolean isO11mov() {
		return this.o11mov;
	}

	public void setO11mov(boolean o11mov) {
		this.o11mov = o11mov;
	}

	public boolean isO12mov() {
		return this.o12mov;
	}

	public void setO12mov(boolean o12mov) {
		this.o12mov = o12mov;
	}

	public boolean isO11mant() {
		return this.o11mant;
	}

	public void setO11mant(boolean o11mant) {
		this.o11mant = o11mant;
	}

	public boolean isO12mant() {
		return this.o12mant;
	}

	public void setO12mant(boolean o12mant) {
		this.o12mant = o12mant;
	}

	public boolean isO13mant() {
		return this.o13mant;
	}

	public void setO13mant(boolean o13mant) {
		this.o13mant = o13mant;
	}

	public boolean isO14mant() {
		return this.o14mant;
	}

	public void setO14mant(boolean o14mant) {
		this.o14mant = o14mant;
	}

	public boolean isO15mant() {
		return this.o15mant;
	}

	public void setO15mant(boolean o15mant) {
		this.o15mant = o15mant;
	}

	public boolean isO01consul() {
		return this.o01consul;
	}

	public void setO01consul(boolean o01consul) {
		this.o01consul = o01consul;
	}

	public boolean isO02consul() {
		return this.o02consul;
	}

	public void setO02consul(boolean o02consul) {
		this.o02consul = o02consul;
	}

	public boolean isO03consul() {
		return this.o03consul;
	}

	public void setO03consul(boolean o03consul) {
		this.o03consul = o03consul;
	}

	public boolean isO04consul() {
		return this.o04consul;
	}

	public void setO04consul(boolean o04consul) {
		this.o04consul = o04consul;
	}

	public boolean isO05consul() {
		return this.o05consul;
	}

	public void setO05consul(boolean o05consul) {
		this.o05consul = o05consul;
	}

	public boolean isO06consul() {
		return this.o06consul;
	}

	public void setO06consul(boolean o06consul) {
		this.o06consul = o06consul;
	}

	public boolean isO07consul() {
		return this.o07consul;
	}

	public void setO07consul(boolean o07consul) {
		this.o07consul = o07consul;
	}

	public boolean isO08consul() {
		return this.o08consul;
	}

	public void setO08consul(boolean o08consul) {
		this.o08consul = o08consul;
	}

	public boolean isO09consul() {
		return this.o09consul;
	}

	public void setO09consul(boolean o09consul) {
		this.o09consul = o09consul;
	}

	public boolean isO10consul() {
		return this.o10consul;
	}

	public void setO10consul(boolean o10consul) {
		this.o10consul = o10consul;
	}

	public boolean isO01rep() {
		return this.o01rep;
	}

	public void setO01rep(boolean o01rep) {
		this.o01rep = o01rep;
	}

	public boolean isO02rep() {
		return this.o02rep;
	}

	public void setO02rep(boolean o02rep) {
		this.o02rep = o02rep;
	}

	public boolean isO03rep() {
		return this.o03rep;
	}

	public void setO03rep(boolean o03rep) {
		this.o03rep = o03rep;
	}

	public boolean isO04rep() {
		return this.o04rep;
	}

	public void setO04rep(boolean o04rep) {
		this.o04rep = o04rep;
	}

	public boolean isO05rep() {
		return this.o05rep;
	}

	public void setO05rep(boolean o05rep) {
		this.o05rep = o05rep;
	}

	public boolean isO06rep() {
		return this.o06rep;
	}

	public void setO06rep(boolean o06rep) {
		this.o06rep = o06rep;
	}

	public boolean isO07rep() {
		return this.o07rep;
	}

	public void setO07rep(boolean o07rep) {
		this.o07rep = o07rep;
	}

	public boolean isO08rep() {
		return this.o08rep;
	}

	public void setO08rep(boolean o08rep) {
		this.o08rep = o08rep;
	}

	public boolean isO09rep() {
		return this.o09rep;
	}

	public void setO09rep(boolean o09rep) {
		this.o09rep = o09rep;
	}

	public boolean isO10rep() {
		return this.o10rep;
	}

	public void setO10rep(boolean o10rep) {
		this.o10rep = o10rep;
	}

	public boolean isO11rep() {
		return this.o11rep;
	}

	public void setO11rep(boolean o11rep) {
		this.o11rep = o11rep;
	}

	public boolean isO12rep() {
		return this.o12rep;
	}

	public void setO12rep(boolean o12rep) {
		this.o12rep = o12rep;
	}

	public boolean isO01pror() {
		return this.o01pror;
	}

	public void setO01pror(boolean o01pror) {
		this.o01pror = o01pror;
	}

	public boolean isO02pror() {
		return this.o02pror;
	}

	public void setO02pror(boolean o02pror) {
		this.o02pror = o02pror;
	}

	public boolean isO03pror() {
		return this.o03pror;
	}

	public void setO03pror(boolean o03pror) {
		this.o03pror = o03pror;
	}

	public boolean isO04pror() {
		return this.o04pror;
	}

	public void setO04pror(boolean o04pror) {
		this.o04pror = o04pror;
	}

	public boolean isO01herra() {
		return this.o01herra;
	}

	public void setO01herra(boolean o01herra) {
		this.o01herra = o01herra;
	}

	public boolean isO02herra() {
		return this.o02herra;
	}

	public void setO02herra(boolean o02herra) {
		this.o02herra = o02herra;
	}

	public boolean isO03herra() {
		return this.o03herra;
	}

	public void setO03herra(boolean o03herra) {
		this.o03herra = o03herra;
	}

	public boolean isO04herra() {
		return this.o04herra;
	}

	public void setO04herra(boolean o04herra) {
		this.o04herra = o04herra;
	}

	public boolean isO05herra() {
		return this.o05herra;
	}

	public void setO05herra(boolean o05herra) {
		this.o05herra = o05herra;
	}

	public boolean isO06herra() {
		return this.o06herra;
	}

	public void setO06herra(boolean o06herra) {
		this.o06herra = o06herra;
	}

	public boolean isO07herra() {
		return this.o07herra;
	}

	public void setO07herra(boolean o07herra) {
		this.o07herra = o07herra;
	}

	public boolean isO08herra() {
		return this.o08herra;
	}

	public void setO08herra(boolean o08herra) {
		this.o08herra = o08herra;
	}

	public boolean isO09herra() {
		return this.o09herra;
	}

	public void setO09herra(boolean o09herra) {
		this.o09herra = o09herra;
	}

	public boolean isO10herra() {
		return this.o10herra;
	}

	public void setO10herra(boolean o10herra) {
		this.o10herra = o10herra;
	}

	public boolean isAcceso01() {
		return this.acceso01;
	}

	public void setAcceso01(boolean acceso01) {
		this.acceso01 = acceso01;
	}

	public boolean isAcceso02() {
		return this.acceso02;
	}

	public void setAcceso02(boolean acceso02) {
		this.acceso02 = acceso02;
	}

	public boolean isAcceso03() {
		return this.acceso03;
	}

	public void setAcceso03(boolean acceso03) {
		this.acceso03 = acceso03;
	}

	public boolean isAcceso04() {
		return this.acceso04;
	}

	public void setAcceso04(boolean acceso04) {
		this.acceso04 = acceso04;
	}

	public boolean isAcceso05() {
		return this.acceso05;
	}

	public void setAcceso05(boolean acceso05) {
		this.acceso05 = acceso05;
	}

	public boolean isAcceso06() {
		return this.acceso06;
	}

	public void setAcceso06(boolean acceso06) {
		this.acceso06 = acceso06;
	}

	public boolean isAcceso07() {
		return this.acceso07;
	}

	public void setAcceso07(boolean acceso07) {
		this.acceso07 = acceso07;
	}

	public boolean isAcceso08() {
		return this.acceso08;
	}

	public void setAcceso08(boolean acceso08) {
		this.acceso08 = acceso08;
	}

	public boolean isAcceso09() {
		return this.acceso09;
	}

	public void setAcceso09(boolean acceso09) {
		this.acceso09 = acceso09;
	}

	public boolean isAcceso10() {
		return this.acceso10;
	}

	public void setAcceso10(boolean acceso10) {
		this.acceso10 = acceso10;
	}

	public boolean isAcceso11() {
		return this.acceso11;
	}

	public void setAcceso11(boolean acceso11) {
		this.acceso11 = acceso11;
	}

	public boolean isAcceso12() {
		return this.acceso12;
	}

	public void setAcceso12(boolean acceso12) {
		this.acceso12 = acceso12;
	}

	public boolean isAcceso13() {
		return this.acceso13;
	}

	public void setAcceso13(boolean acceso13) {
		this.acceso13 = acceso13;
	}

	public boolean isAcceso14() {
		return this.acceso14;
	}

	public void setAcceso14(boolean acceso14) {
		this.acceso14 = acceso14;
	}

	public boolean isAcceso15() {
		return this.acceso15;
	}

	public void setAcceso15(boolean acceso15) {
		this.acceso15 = acceso15;
	}

}
